services:
  web:
    image: restapi.azurecr.io/samples/django-rest:v7
    container_name: django_app
    ports:
      - "80:80"
    environment:
      - DJANGO_ENV=prod
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - STORAGE_KEY=${STORAGE_KEY}
      - CLOUDFLARE_TURNSTILE_SECRET_KEY=${CLOUDFLARE_TURNSTILE_SECRET_KEY}
      - EMAIL_APP_KEY=${EMAIL_APP_KEY}
    depends_on:
      - redis
    networks:
      - default

  redis:
    image: redis:7.2.1
    ports:
      - "6379:6379"

    restart: always
    networks:
      - default

networks:
  default:
    driver: bridge
