# https://docs.docker.com/compose/gettingstarted/
services:
  rest_api_django:
    build: .
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    depends_on:
      - redis
      - celery

  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: celery -A backend worker --loglevel=info
    depends_on:
      - redis
