# https://github.com/casey/just
serve mode="dev": migrate inicializacion
    DJANGO_ENV={{mode}} docker compose up --build

migrate: fmt
    uv run ./src/manage.py makemigrations
    uv run ./src/manage.py migrate --run-syncdb

check: fmt
    ruff check ./

test: migrate check fmt
    uv run ./src/manage.py test ./src/

fmt:
    ruff format ./

shell:
    uv run ./src/manage.py shell


inicializacion: 
    uv run ./src/scripts/inicializacion_db.py
