# https://github.com/casey/just

serve mode="dev": migrate
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ "{{mode}}" = "dev" ]; then \
        cd ./src/
        DJANGO_ENV={{mode}} uv run ./manage.py runserver  
        wait
    elif [ "{{mode}}" = "prod" ]; then \
        docker compose up --build
    fi

celery:
    cd ./src/ && celery -A backend worker --loglevel=info 

redis:
    docker run -d -p 6379:6379 redis:latest


migrate: fmt
    uv run ./src/manage.py makemigrations
    uv run ./src/manage.py migrate

check: fmt
    ruff check ./

test: migrate check fmt
    uv run ./src/manage.py test ./src/

fmt:
    ruff format ./

shell:
    uv run ./src/manage.py shell
