# Generated by Django 5.1.2 on 2024-11-01 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Escultor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                (
                    "foto",
                    models.FileField(blank=True, null=True, upload_to="perfiles/"),
                ),
                ("bibliografia", models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="Escultura",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.CharField(max_length=300)),
                ("fecha_creacion", models.DateField()),
                ("qr", models.FileField(blank=True, null=True, upload_to="qr/")),
            ],
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("descripcion", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Imagen",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                (
                    "imagen",
                    models.FileField(blank=True, null=True, upload_to="imagenes/"),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lugar",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tematica",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Votante",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("correo", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Escultorevento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "escultor_id",
                    models.ForeignKey(
                        db_column="escultor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.escultor",
                    ),
                ),
                (
                    "evento_id",
                    models.ForeignKey(
                        db_column="evento_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.evento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EsculturaImagen",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "escultura_id",
                    models.ForeignKey(
                        db_column="escultura_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.escultura",
                    ),
                ),
                (
                    "imagen_id",
                    models.ForeignKey(
                        db_column="imagen_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.imagen",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="evento",
            name="lugar_id",
            field=models.ForeignKey(
                db_column="lugar_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.lugar",
            ),
        ),
        migrations.AddField(
            model_name="escultor",
            name="pais_id",
            field=models.ForeignKey(
                db_column="pais_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.pais",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="tematica_id",
            field=models.ForeignKey(
                db_column="tematica_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.tematica",
            ),
        ),
        migrations.CreateModel(
            name="VotoEscultor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "escultor_id",
                    models.ForeignKey(
                        db_column="escultor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.escultor",
                    ),
                ),
                (
                    "votante_id",
                    models.ForeignKey(
                        db_column="votante_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.votante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VotoEscultura",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "escultura_id",
                    models.ForeignKey(
                        db_column="escultura_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.escultura",
                    ),
                ),
                (
                    "votante_id",
                    models.ForeignKey(
                        db_column="votante_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.votante",
                    ),
                ),
            ],
        ),
    ]
