# Generated by Django 5.1 on 2024-10-11 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdminSistema",
        ),
    ]
