# Generated by Django 5.1 on 2024-09-14 05:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Adm_sistemas",
            new_name="AdminSistema",
        ),
    ]
