# Generated by Django 5.1 on 2024-08-28 22:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="UserCustom",
        ),
    ]
