# Generated by Django 5.1.2 on 2024-10-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_escultura_escultor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="pais",
            name="iso",
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
