# Generated by Django 5.1.2 on 2024-10-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_pais_iso"),
    ]

    operations = [
        migrations.AddField(
            model_name="escultor",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
