# Generated by Django 5.1 on 2024-09-06 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_usercustom_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adm_sistemas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "correo",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Escultor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "correo",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "foto",
                    models.FileField(blank=True, null=True, upload_to="perfiles/"),
                ),
                ("bibliografia", models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="Escultorevento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "escultor_id",
                    models.ForeignKey(
                        db_column="escultor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.escultor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Escultura",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("fecha_creacion", models.DateField()),
                ("qr", models.FileField(blank=True, null=True, upload_to="qr/")),
            ],
        ),
        migrations.CreateModel(
            name="EsculturaImagen",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "escultura_id",
                    models.ForeignKey(
                        db_column="escultura_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.escultura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Imagen",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                (
                    "imagen",
                    models.FileField(blank=True, null=True, upload_to="imagenes/"),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lugar",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tematica",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Visitante",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "correo",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VotoEscultor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="VotoEscultura",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "escultura_id",
                    models.ForeignKey(
                        db_column="escultura_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.escultura",
                    ),
                ),
                (
                    "visitante_id",
                    models.ForeignKey(
                        db_column="visitante_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.visitante",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Snippet",
        ),
        migrations.AddField(
            model_name="escultorevento",
            name="evento_id",
            field=models.ForeignKey(
                db_column="evento_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.evento",
            ),
        ),
        migrations.AddField(
            model_name="esculturaimagen",
            name="imagen_id",
            field=models.ForeignKey(
                db_column="imagen_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.imagen",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="lugar_id",
            field=models.ForeignKey(
                db_column="lugar_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.lugar",
            ),
        ),
        migrations.AddField(
            model_name="escultor",
            name="pais_id",
            field=models.ForeignKey(
                db_column="pais_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.pais",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="tematica_id",
            field=models.ForeignKey(
                db_column="tematica_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.tematica",
            ),
        ),
        migrations.AddField(
            model_name="votoescultor",
            name="escultor_id",
            field=models.ForeignKey(
                db_column="escultor_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.escultor",
            ),
        ),
        migrations.AddField(
            model_name="votoescultor",
            name="visitante_id",
            field=models.ForeignKey(
                db_column="visitante_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.visitante",
            ),
        ),
    ]
