# Generated by Django 5.1.2 on 2024-11-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_escultor_fecha_nacimiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="escultor",
            name="apellido",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="escultor",
            name="nombre",
            field=models.CharField(max_length=40),
        ),
    ]
