# Generated by Django 5.1 on 2024-09-06 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_adm_sistemas_escultor_escultorevento_escultura_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserCustom",
        ),
    ]
