# Generated by Django 5.1.2 on 2024-11-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_escultor_apellido_alter_escultor_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="escultura",
            name="fecha_creacion",
            field=models.DateField(auto_now_add=True),
        ),
    ]
