# Generated by Django 5.1.2 on 2024-11-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_escultura_fecha_creacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="escultura",
            name="fecha_creacion",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
