# Generated by Django 5.1.2 on 2024-11-01 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_alter_escultura_fecha_creacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagen",
            name="fecha",
        ),
        migrations.AddField(
            model_name="imagen",
            name="escultura_id",
            field=models.ForeignKey(
                db_column="escultura_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.escultura",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="imagen",
            name="fecha_creacion",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name="EsculturaImagen",
        ),
    ]
