venv:
    source .venv/bin/activate.fish

serve:
    uv run ruff format ./
    uv run ./manage.py migrate
    uv run ./manage.py runserver

test:
    uv run ./manage.py migrate
    uv run ./manage.py test

check:
    ruff check ./

fmt:
    ruff format ./
