venv:
    source .venv/bin/activate.fish

serve:
    uv run ruff format ./
    uv run ./manage.py makemigrations
    uv run ./manage.py migrate
    uv run ./manage.py runserver

migrate:
    uv run ./manage.py makemigrations
    uv run ./manage.py migrate

test:
    uv run ./manage.py migrate
    uv run ./manage.py test

check:
    ruff check ./

fmt:
    ruff format ./

shell:
    uv run ./manage.py shell
