-- USER
INSERT INTO "auth_user" (
    "id",
    "password",
    "last_login",
    "is_superuser",
    "username",
    "first_name",
    "email",
    "is_staff",
    "is_active",
    "date_joined",
    "last_name"
) VALUES (
    1,
    'pbkdf2_sha256$870000$q7jZZSTbg7cV2RdU6ooNko$4k5FrQg30KnKPyG2M2yNC5filhPeaxCOC2ZKri0rZCs=',
    NULL,
    true,
    'admin',
    '',
    'admin@admin.com',
    true,
    true,
    '2024-11-01 22:17:39.218211',
    ''
);

-- PAIS
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Afganistán','AF');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Islas Gland','AX');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Albania','AL');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Alemania','DE');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Andorra','AD');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Angola','AO');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Anguilla','AI');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Antártida','AQ');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Antigua y Barbuda','AG');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Antillas Holandesas','AN');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Arabia Saudí','SA');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Argelia','DZ');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Argentina','AR');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Armenia','AM');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Aruba','AW');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Australia','AU');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Austria','AT');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Azerbaiyán','AZ');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Bahamas','BS');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Bahréin','BH');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Bangladesh','BD');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Barbados','BB');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Bielorrusia','BY');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Bélgica','BE');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Belice','BZ');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Benin','BJ');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Bermudas','BM');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Bhután','BT');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Bolivia','BO');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Bosnia y Herzegovina','BA');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Botsuana','BW');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Isla Bouvet','BV');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Brasil','BR');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Brunéi','BN');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Bulgaria','BG');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Burkina Faso','BF');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Burundi','BI');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Cabo Verde','CV');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Islas Caimán','KY');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Camboya','KH');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Camerún','CM');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Canadá','CA');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('República Centroafricana','CF');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Chad','TD');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('República Checa','CZ');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Chile','CL');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('China','CN');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Chipre','CY');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Isla de Navidad','CX');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Ciudad del Vaticano','VA');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Islas Cocos','CC');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Colombia','CO');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Comoras','KM');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('República Democrática del Congo','CD');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Congo','CG');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Islas Cook','CK');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Corea del Norte','KP');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Corea del Sur','KR');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Costa de Marfil','CI');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Costa Rica','CR');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Croacia','HR');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Cuba','CU');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Dinamarca','DK');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Dominica','DM');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('República Dominicana','DO');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Ecuador','EC');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Egipto','EG');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('El Salvador','SV');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Emiratos Árabes Unidos','AE');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Eritrea','ER');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Eslovaquia','SK');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Eslovenia','SI');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('España','ES');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Islas ultramarinas de Estados Unidos','UM');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Estados Unidos','US');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Estonia','EE');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Etiopía','ET');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Islas Feroe','FO');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Filipinas','PH');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Finlandia','FI');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Fiyi','FJ');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Francia','FR');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Gabón','GA');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Gambia','GM');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Georgia','GE');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Islas Georgias del Sur y Sandwich del Sur','GS');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Ghana','GH');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Gibraltar','GI');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Granada','GD');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Grecia','GR');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Groenlandia','GL');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Guadalupe','GP');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Guam','GU');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Guatemala','GT');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Guayana Francesa','GF');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Guinea','GN');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Guinea Ecuatorial','GQ');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Guinea-Bissau','GW');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Guyana','GY');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Haití','HT');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Islas Heard y McDonald','HM');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Honduras','HN');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Hong Kong','HK');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Hungría','HU');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('India','IN');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Indonesia','ID');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Irán','IR');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Iraq','IQ');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Irlanda','IE');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Islandia','IS');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Israel','IL');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Italia','IT');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Jamaica','JM');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Japón','JP');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Jordania','JO');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Kazajstán','KZ');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Kenia','KE');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Kirguistán','KG');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Kiribati','KI');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Kuwait','KW');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Laos','LA');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Lesotho','LS');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Letonia','LV');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Líbano','LB');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Liberia','LR');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Libia','LY');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Liechtenstein','LI');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Lituania','LT');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Luxemburgo','LU');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Macao','MO');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('ARY Macedonia','MK');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Madagascar','MG');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Malasia','MY');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Malawi','MW');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Maldivas','MV');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Malí','ML');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Malta','MT');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Islas Malvinas','FK');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Islas Marianas del Norte','MP');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Marruecos','MA');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Islas Marshall','MH');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Martinica','MQ');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Mauricio','MU');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Mauritania','MR');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Mayotte','YT');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('México','MX');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Micronesia','FM');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Moldavia','MD');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Mónaco','MC');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Mongolia','MN');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Montserrat','MS');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Mozambique','MZ');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Myanmar','MM');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Namibia','NA');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Nauru','NR');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Nepal','NP');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Nicaragua','NI');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Níger','NE');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Nigeria','NG');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Niue','NU');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Isla Norfolk','NF');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Noruega','NO');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Nueva Caledonia','NC');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Nueva Zelanda','NZ');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Omán','OM');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Países Bajos','NL');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Pakistán','PK');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Palau','PW');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Palestina','PS');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Panamá','PA');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Papúa Nueva Guinea','PG');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Paraguay','PY');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Perú','PE');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Islas Pitcairn','PN');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Polinesia Francesa','PF');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Polonia','PL');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Portugal','PT');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Puerto Rico','PR');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Qatar','QA');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Reino Unido','GB');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Reunión','RE');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Ruanda','RW');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Rumania','RO');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Rusia','RU');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Sahara Occidental','EH');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Islas Salomón','SB');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Samoa','WS');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Samoa Americana','AS');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('San Cristóbal y Nevis','KN');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('San Marino','SM');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('San Pedro y Miquelón','PM');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('San Vicente y las Granadinas','VC');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Santa Helena','SH');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Santa Lucía','LC');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Santo Tomé y Príncipe','ST');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Senegal','SN');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Serbia y Montenegro','CS');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Seychelles','SC');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Sierra Leona','SL');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Singapur','SG');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Siria','SY');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Somalia','SO');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Sri Lanka','LK');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Suazilandia','SZ');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Sudáfrica','ZA');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Sudán','SD');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Suecia','SE');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Suiza','CH');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Surinam','SR');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Svalbard y Jan Mayen','SJ');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Tailandia','TH');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Taiwán','TW');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Tanzania','TZ');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Tayikistán','TJ');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Territorio Británico del Océano Índico','IO');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Territorios Australes Franceses','TF');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Timor Oriental','TL');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Togo','TG');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Tokelau','TK');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Tonga','TO');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Trinidad y Tobago','TT');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Túnez','TN');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Islas Turcas y Caicos','TC');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Turkmenistán','TM');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Turquía','TR');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Tuvalu','TV');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Ucrania','UA');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Uganda','UG');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Uruguay','UY');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Uzbekistán','UZ');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Vanuatu','VU');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Venezuela','VE');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Vietnam','VN');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Islas Vírgenes Británicas','VG');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Islas Vírgenes de los Estados Unidos','VI');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Wallis y Futuna','WF');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Yemen','YE');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Yibuti','DJ');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Zambia','ZM');
INSERT INTO "app_pais" ( nombre, iso) VALUES ('Zimbabue','ZW');


-- ESCULTOR
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('eloisafortuny@example.org','1tNmPVjYcqI539a3BMV4JlCQHEYVmnMvi','Voluptates expedita fugit. Nemo nulla autem recusandae veritatis quam. Eum libero quas occaecati. Dolorum laudantium quaerat nostrum quae qui.',77,'2004-10-11','Collado','Sarita');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('guitartencarnita@example.net','15viwh8wJMz5I_9SlCitqBf5mNy2b2-Yr','Omnis fuga beatae molestias. In distinctio nostrum molestiae maxime eius suscipit. Dolore excepturi accusamus sapiente. Blanditiis enim quam magni.',42,'1993-04-27','Nebot','Juan Carlos');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('victor27@example.org','1BzU5CHb4ZNyN1qrgSTbSn4PdWClmoiJd','Similique ipsa natus. Dolores assumenda animi similique sapiente. Blanditiis autem ipsa asperiores.',156,'1988-09-19','Isern','Casandra');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('nparejo@example.org','1Fpv7S6isAR2zuxZrtI35rYVsGwqfW-lN','Omnis laudantium eaque autem expedita dignissimos vitae. Asperiores mollitia ratione omnis.',223,'2006-01-22','Comas','Xavier');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('bertrancesar@example.com','1Hjp3OH24QFoL-P3x-QLBYqI35KqqwjJa','Similique vel aliquid aut odit odio dolores. Repellendus dolorum adipisci voluptatum quibusdam ullam laudantium.',216,'1999-12-22','Roda','Duilio');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('mirocalixta@example.com','1I1SJqKMbq7SkUoogV2xPOao6-7LmGuaA','Iste qui perspiciatis ut modi ea eos. Fugit minima itaque eum quisquam ducimus.',116,'1999-02-24','Blázquez','Maricruz');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('segoviawalter@example.org','1LhfU3cgWHKOL-QQBdJhdcwCQoYolaEmd','Repellendus facere voluptate sit. Odit ratione provident saepe. Voluptatem dolor quis eveniet non adipisci distinctio.',154,'1988-03-05','Lerma','Buenaventura');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('adolfo06@example.com','1LlWVos35FzcEFNOPg0FuOReAvG8pvdul','Autem fuga perferendis quam voluptates. Atque voluptates reprehenderit modi sunt. Incidunt dolorem non soluta impedit.',5,'2005-09-15','Sierra','Fernando');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('baezjaviera@example.com','1PP9p5JOwj6-6JbgkqJsk1vQ6GVKcokjW','Ipsa exercitationem dolores dicta. Saepe accusantium asperiores facilis unde fugiat.',35,'1981-02-22','Espinosa','Florentino');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('yolandapadilla@example.org','1U8etR1tJttuX1eK_Yoe4igyEN2icMHg4','Explicabo ex dolorem maxime nisi quia. Laboriosam magnam veniam est repellendus dolorem. Dolor aut maiores. Officia alias earum earum architecto.',31,'1990-11-12','Galván','Roberta');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('qbertran@example.net','1UZuVuxOdlT3XckN27dqnNBNehxVcJAUm','Voluptatum reiciendis repellat inventore. Placeat enim sed deserunt ullam corporis. Beatae quia dignissimos quaerat quam.',79,'2006-01-24','Gimeno','Rodolfo');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('bonillaluciano@example.com','1YhOdBlbkVFD8HRwLmWckYtR4mlDhOfim','Neque repudiandae corporis omnis velit voluptate. Neque nulla voluptates odit aliquam dolorem sapiente. Accusantium reiciendis exercitationem nisi similique.',175,'1997-03-01','Núñez','Noelia');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('escrivapaola@example.org','1Yz015tLau5lS7TIbCyX2FeHKMqHImXwn','Voluptas et sed blanditiis officia quam dolores. Ducimus facilis officiis quidem quod consequuntur dolorum ducimus. Possimus dicta rem illum.',233,'1984-06-29','Rocha','Tito');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('jpozo@example.org','1a0xuXxXI7qjCMk0wPpviIoDXfhH_Vesj','Eum reprehenderit molestiae cum. Quas ipsam saepe nihil. Similique accusamus quia perspiciatis beatae provident ex. Atque quod quod.',8,'2003-09-11','Valenzuela','Clotilde');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('pcoca@example.org','1eMEwIeGkslF8JrGwxcBC5kVZxyXcqdZV','Perferendis veniam necessitatibus dolor omnis vero veritatis id. Reiciendis doloremque sit nesciunt quod.',144,'1986-06-29','Porta','Cayetana');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('desiderio51@example.com','1iAF3V7mSvJkLVySWTQoxGjUAk2fGoyUQ','Ex voluptate illum impedit doloribus tenetur. Eos rem nihil delectus fugiat. Neque quos numquam.',58,'1995-06-17','Armengol','Socorro');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('iquerol@example.com','1saHemEvjjNf8U7l9Dg9ry_PJ2lCtCbpg','Accusantium facere vitae quos. Assumenda saepe molestias.',148,'1983-11-17','Bayo','Leonel');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('pintorlara@example.org','1swuWyt64fdQ2S6_D3oIf37jQYhqZsu1a','Accusamus id culpa accusantium ex numquam. Error ipsum assumenda amet minima nobis. Quos minus repellat maiores.',147,'1998-06-06','Mulet','Carina');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('pratsjuan-pablo@example.net','12xQ2nq9GAl0cePulAFxWKLPwhy6DyiGp','Repudiandae eum fugit recusandae nostrum voluptate pariatur. Nobis similique fugit.',206,'1980-10-10','Carretero','Delia');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('noemi57@example.com','16vnBm5QGgJ-T0TPAeRHyjZSl-f3Sq7S5','Officia assumenda dignissimos voluptates cupiditate iusto. Laboriosam ipsum nihil facere adipisci nam.',184,'1981-10-09','Navas','Agapito');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('barredaedgar@example.net','17kK9-zQF6RAElvfXhYQRveVs-ssF_DYh','Aperiam perferendis at fugit. Enim architecto quia mollitia doloremque doloremque autem.',13,'1999-07-15','Galindo','Ani');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('jose-carlosguerrero@example.com','1GvojOG-CtXOwaQj5vU_8R0sSb90c5QuP','Sapiente voluptates ex iure ipsam ad. Magni aut alias expedita hic. Consequatur iusto quia eligendi necessitatibus.',27,'1989-04-02','Ferrando','Severino');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('enavas@example.net','1JX1YoYa26J_xMZ5uWwlYNGcpWiX0F2t4','Voluptas perferendis laborum rerum quam. Culpa necessitatibus maiores repellat vel deleniti nihil.',99,'1988-01-11','Cornejo','Manolo');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('teodosio60@example.com','1ObEMTUsndsbZrUwxFLOmkOGynDHQtREJ','Temporibus sint ullam debitis praesentium recusandae quam.',131,'2001-06-20','Alcolea','Nerea');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('atiliozapata@example.org','1PSVHCf8lt0esMKM0fXglBIOEGO8kHggj','Mollitia rem corporis dolorem sed doloribus magni modi. Neque quod unde dolorum. Occaecati sed perspiciatis pariatur itaque pariatur. Similique nulla doloremque excepturi ipsa doloribus.',52,'1984-01-17','Esteban','Raimundo');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('vizcainoconsuelo@example.com','1hty4nbw06ifL7rxnwDPjE_wWOUogIGfJ','Consequuntur maxime alias alias et. Molestiae ut adipisci exercitationem. Quisquam expedita incidunt eaque delectus.',88,'1986-07-23','Salvà','Claudio');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('nsaez@example.org','1pkbqdnfqMTg6TJK_OmLZ0HvML48fWoRo','Magnam cumque reprehenderit dolorum.',83,'2000-09-15','Cuadrado','Dalila');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('leocadio71@example.net','1stPIgXmE9-O8r2X6EoYDGPAANjHfNQDA','Iusto ullam aliquid eius tempora. Consequuntur nostrum unde iure error.',17,'1991-11-30','Cámara','Dionisio');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('ceciliooller@example.org','12Wm2vouxGBRGu_COunS97knP75dcfDXe','Deserunt non praesentium tenetur. Quaerat cupiditate quod quisquam ad fuga.',179,'2004-10-09','Tejada','Armando');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('victor-manuelacosta@example.com','1FmzkhbkZJqIKgpIcXdhqre3rL51qLZs4','Laborum temporibus ad quibusdam quia nesciunt. Temporibus a consectetur esse. Dolore doloremque at facere vel odit et esse.',16,'1979-04-13','Grau','Paloma');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('acostaevaristo@example.org','1GDYWDAtef3p7q8qFaB3Fuu1jLx2qLgAO','Quibusdam iusto ex repellendus quos. Dolor voluptates doloremque eaque eius. Eveniet fuga laboriosam.',145,'2006-02-04','Girona','Moisés');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('erasmotomas@example.org','1V1NoFkHeZ5BGN-FVsjGQ2GilEu80uez3','Est totam dolores minima sit omnis. Cupiditate quod ratione fugiat.',167,'1984-11-01','Ángel','Felipe');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('eloisa08@example.com','1ZPAw5wswWmCAY2EiftolZw3a_Rulp1gh','Dicta doloribus neque delectus libero nisi quisquam. Natus eum distinctio ex autem. Neque eos iste eveniet consectetur ipsa.',135,'1994-02-25','Solís','Dolores');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('zbastida@example.net','1eQXUxN545dTapQJ_3wxYmdyyKDJBjQHU','Eaque ad autem dolorum suscipit corporis officiis. Fuga similique reprehenderit occaecati perferendis delectus.',105,'2006-04-15','Mate','César');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('pepe40@example.com','1x7kg1MAcRWLjU5i7vZ4XVANufjHI6qxx','Error quidem ipsa asperiores a quia labore. Quasi molestiae modi maxime temporibus quis.',79,'1985-01-31','Buendía','Alonso');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('prudenciacuevas@example.net','1EHFO3TQVzKOKxLzlSkvIspy4-ibMQbm2','Itaque voluptatibus dicta eaque suscipit debitis nemo. Eum officiis est soluta porro ex quidem. Architecto omnis quaerat quis inventore sequi.',60,'1998-11-11','Murillo','Ambrosio');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('serrajulieta@example.org','1K_W819a2Zhyp-tSINgW3l71TrMkt4MJE','Id consequatur deleniti quibusdam illum deleniti fugit eius. Neque ea assumenda impedit deserunt laudantium facere.',114,'1983-10-21','Frutos','Lara');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('ycalvo@example.org','1RyjSNIjcDaa1hAEj1BdRwFMU1dM6Jtob','Ducimus dolorem sunt occaecati.',195,'1984-04-01','Espejo','Teo');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('langel@example.net','1bMs-v2MeuQPmeX9OsN-XElGMD4-OEEjk','Similique quasi veniam saepe quod commodi quibusdam.',65,'2002-04-11','Canals','Estela');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('vpizarro@example.org','166VM4JqpVZvvp5Fygs387AzA2CYjJr2Y','Perferendis impedit accusamus vel rerum veritatis. Consequuntur magnam ducimus voluptas. Quam eaque esse repudiandae sit.',86,'1993-01-10','Cazorla','Vasco');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('reciojose-manuel@example.org','1Dy0vNHRs31TPkiM2uJ6no6xmRNBcWeKx','Facere voluptas similique ab dignissimos. Natus nemo aliquid mollitia. Odio quasi molestiae quisquam sequi expedita delectus.',96,'1995-09-05','Aznar','Eligia');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('flucena@example.org','1NVZ3Im1ghmoiEiStuFi8XeLlDOmryEZZ','Earum ducimus dolorem pariatur incidunt aperiam aut. Fugiat quibusdam tempore fugit similique corrupti distinctio et. Repellendus vel fuga sed.',189,'2002-04-09','Feliu','Marc');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('sanmartinbenigno@example.net','1XqMsY5CFQqRvLF_hREwFjb0TXyxWDfy9','Maiores assumenda dolore alias aspernatur ullam. Rem sint fugit ipsum nemo rerum rerum. Vel inventore unde cum aspernatur.',51,'1996-09-09','Cabañas','Dani');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('zzabala@example.org','1dc--YrF4PD2amTz7RIGN1BOAvVNAjLYg','Perferendis architecto accusantium. Blanditiis consequuntur perferendis minus possimus accusamus. Velit placeat dolore qui.',5,'1997-04-18','Valcárcel','Delia');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('alfonsovidal@example.net','1pd15EqM_ChgdK40eS0HsqMPVmpRNtT3C','Vel molestiae quae veniam corporis. Nisi alias at inventore minima illum in quas. Provident laborum suscipit iusto magni laudantium. Minus illo quisquam.',155,'1996-10-12','Velázquez','Hector');
INSERT INTO "app_escultor" ( correo,foto, bibliografia, pais_id, fecha_nacimiento,nombre, apellido) VALUES ('gonzalo11@gmail.com','perfiles/preparacion.jpg','dskdsfndfsndsfdsfdf',1,'2000-11-09','saucedo','gonzalo');


-- LUGAR
INSERT INTO "app_lugar" (nombre, descripcion) VALUES ('Zona Automotrices','Soluta fuga quae accusamus provident. Impedit iusto illo nemo. Esse ratione corrupti non ut.');
INSERT INTO "app_lugar" (nombre, descripcion) VALUES ('Zona Artesanos','Ipsam quod modi alias neque iure. Quos saepe debitis quo nulla.');
INSERT INTO "app_lugar" (nombre, descripcion) VALUES ('Zona Emprendedores','Quos maxime consequatur quasi numquam expedita provident.');
INSERT INTO "app_lugar" (nombre, descripcion) VALUES ('Zona Cancha de basket','Assumenda iure necessitatibus optio nostrum dolorum. Cupiditate culpa culpa commodi soluta.');
INSERT INTO "app_lugar" (nombre, descripcion) VALUES ('Zona Cancha de voley','Blanditiis itaque quae consequuntur iure earum.');
INSERT INTO "app_lugar" (nombre, descripcion) VALUES ('Zona Gastronomias','Accusantium voluptate aperiam nisi aspernatur.');
INSERT INTO "app_lugar" (nombre, descripcion) VALUES ('Zona Pymes','Id quam assumenda sed. Impedit quod quae provident aut. Deleniti provident minus a unde veritatis ea.');
INSERT INTO "app_lugar" (nombre, descripcion) VALUES ('Zona Prensa','Cumque sit nobis laboriosam natus expedita modi. Iste saepe tenetur pariatur laborum. Doloribus mollitia officia molestias doloribus corrupti quae.');
INSERT INTO "app_lugar" (nombre, descripcion) VALUES ('Zona Pista de atletismo','Corrupti molestiae inventore iusto itaque eligendi aut. Iusto corporis eaque eos quae sed. Dolores officiis ratione saepe nostrum. Eum vel fuga accusantium nam laborum quo tempora.');
INSERT INTO "app_lugar" (nombre, descripcion) VALUES ('Zona Puestos de Salud','Repellat praesentium doloribus commodi tempora veritatis. Officia repellendus pariatur distinctio veniam autem blanditiis ex. Voluptate illo rem quia fuga. Doloribus id fugit reiciendis quas natus exercitationem.');

-- TEMATICA
INSERT INTO "app_tematica"  ( nombre, descripcion) VALUES ('Naturaleza y Paisaje','Exercitationem minus similique eveniet blanditiis necessitatibus. Blanditiis accusantium provident suscipit.');
INSERT INTO "app_tematica"  ( nombre, descripcion) VALUES ('Identidad Cultural','Molestiae saepe totam ex aliquam mollitia consequuntur. Accusamus accusamus corrupti veritatis. Error hic quod molestiae beatae illum.');
INSERT INTO "app_tematica"  ( nombre, descripcion) VALUES ('Tecnología y Futuro','Et id earum nulla. Excepturi ab harum possimus. Necessitatibus exercitationem numquam ipsam nam doloribus.');
INSERT INTO "app_tematica"  ( nombre, descripcion) VALUES ('Memoria Histórica','Dolore hic qui. Facere magnam rerum aperiam dolores perspiciatis animi accusamus. Laudantium pariatur eveniet quae eligendi dolor.');
INSERT INTO "app_tematica"  ( nombre, descripcion) VALUES ('Abstracción y Color','Nemo aliquam commodi unde cumque saepe culpa. Accusantium quas aut culpa. Nostrum dolores explicabo corrupti accusamus aperiam ipsum.');
INSERT INTO "app_tematica"  ( nombre, descripcion) VALUES ('Diversidad y Género','Eveniet debitis tempore nostrum. Consequatur animi ratione quas corporis ut esse eos. Mollitia animi praesentium magnam aperiam expedita.');
INSERT INTO "app_tematica"  ( nombre, descripcion) VALUES ('Ecología y Sustentabilidad','Unde corporis laborum. Sint itaque tenetur sint. Voluptatibus delectus eligendi corrupti quia tempora dolore.');
INSERT INTO "app_tematica"  ( nombre, descripcion) VALUES ('Exploración Espacial','Veritatis aspernatur expedita asperiores magnam neque quaerat. Quisquam sed animi excepturi beatae. Quae placeat ipsa aliquid dolor beatae.');
INSERT INTO "app_tematica"  ( nombre, descripcion) VALUES ('Misticismo y Religión','Eos animi temporibus. Nesciunt tempore facilis excepturi ducimus expedita deleniti itaque. Laborum fugit minima rerum odit neque ipsam.');
INSERT INTO "app_tematica"  ( nombre, descripcion) VALUES ('Migración y Fronteras','Quidem maxime animi vitae hic. Inventore magnam ex magni et. Minima dolorum nesciunt placeat tempora odit odio.');
INSERT INTO "app_tematica"  ( nombre, descripcion) VALUES ('Arte y Ciencia','Incidunt sit omnis consequuntur magnam vel. Debitis odit pariatur nihil soluta pariatur cumque reprehenderit. Eaque sit ducimus.');
INSERT INTO "app_tematica"  ( nombre, descripcion) VALUES ('Sueños y Realidad','Impedit nemo quaerat ipsum impedit expedita corporis. At esse repellendus quia officiis nulla. Ducimus harum officiis culpa unde eligendi.');
INSERT INTO "app_tematica"  ( nombre, descripcion) VALUES ('Tiempo y Espacio','Quaerat nesciunt animi iure a odit iste reprehenderit. Reprehenderit rerum velit odio.');
INSERT INTO "app_tematica"  ( nombre, descripcion) VALUES ('El Cuerpo Humano','Ipsum quidem recusandae voluptatem fuga necessitatibus. Iste soluta odit impedit optio ex.');
INSERT INTO "app_tematica"  ( nombre, descripcion) VALUES ('Emociones y Expresiones','Cum dolores dicta eaque. Hic consequuntur magnam accusamus.');

-- VOTANTE
INSERT INTO "app_votante" ( correo) VALUES ('tguerra@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('joaquinripoll@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('amor56@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('mmorillo@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('dan02@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('galabaeza@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('vpi@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('noemi31@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('vilaltanayara@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('jovitaisern@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('wmosquera@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('florinda96@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('epi@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('saturnino06@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('romancarrion@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('bgarrido@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('rolando01@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('jesussevillano@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('moraledapepe@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('reynaldocasanovas@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('mhidalgo@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('german44@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('qbarbero@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('angel26@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('severianofiguerola@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('dora10@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('alvaro63@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('blazquezsaturnino@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('maricelasarabia@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('xvinas@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('emigdio64@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('germanarana@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('apoloniagallego@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('pisern@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('josevillegas@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('luz06@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('maria-jesusblasco@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('escolanoroque@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('anibal82@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('linabarreda@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('walfaro@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('farco@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('lucio69@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('pesparza@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('candelarioalfaro@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('kpont@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('roxana75@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('lazarorosell@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('qsantos@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('farregui@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('sabaternicodemo@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('eleuteriobello@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('dvillaverde@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('jennifervalera@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('geraldo06@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('qbas@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('eladio92@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('aescalona@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('farnau@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('ponsnoa@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('jose-ramonlucas@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('valverdenando@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('evasanchez@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('serafina74@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('lamor@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('calvetolimpia@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('vcadenas@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('suarezclarisa@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('eusebio48@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('marcelalorenzo@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('sarita81@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('dboada@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('venceslas00@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('cescolano@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('usoria@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('octavia93@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('ainaraamador@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('procha@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('noe79@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('marmolinigo@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('guadalupepizarro@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('vriquelme@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('loidamalo@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('leonardohuertas@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('zaguilar@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('guijarroeulalia@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('mariscaljose-luis@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('ggual@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('baezajacinto@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('inmaculadaagusti@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('alberolawilfredo@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('emiliamartorell@example.net');
INSERT INTO "app_votante" ( correo) VALUES ('usanmiguel@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('yesicapalacios@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('pvalenzuela@example.com');
INSERT INTO "app_votante" ( correo) VALUES ('emilianarojas@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('pradonarcisa@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('gilberto04@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('evitaalberola@example.org');
INSERT INTO "app_votante" ( correo) VALUES ('sagudo@example.com');

-- EVENTO
INSERT INTO "app_evento" ( nombre, fecha_inicio, fecha_fin, descripcion, lugar_id, tematica_id) VALUES ('Concurso Internacional de Escultura','2024-11-01','2024-11-07','Quisquam error voluptatum nisi amet aperiam. Ipsum perspiciatis impedit dignissimos.',5,6);
INSERT INTO "app_evento" ( nombre, fecha_inicio, fecha_fin, descripcion, lugar_id, tematica_id) VALUES ('Exposiciones de Arte','2024-11-01','2024-11-07','Voluptas minima quos blanditiis magni culpa dicta. Perspiciatis voluptatibus omnis quo corrupti. Rerum ratione quo sint.',10,13);
INSERT INTO "app_evento" ( nombre, fecha_inicio, fecha_fin, descripcion, lugar_id, tematica_id) VALUES ('Talleres y Capacitaciones','2024-11-01','2024-11-07','Iure nostrum natus accusamus. Esse ab autem eum.',1,12);
INSERT INTO "app_evento" ( nombre, fecha_inicio, fecha_fin, descripcion, lugar_id, tematica_id) VALUES ('Conferencias y Charlas','2024-11-01','2024-11-07','Occaecati odit dolore molestias amet iusto. Aperiam tenetur consequatur excepturi molestias eligendi.',3,2);
INSERT INTO "app_evento" ( nombre, fecha_inicio, fecha_fin, descripcion, lugar_id, tematica_id) VALUES ('Recorridos Guiados','2024-11-01','2024-11-07','Nemo tempora non similique dolorum fugiat aliquam voluptatum. Nemo dolore sint maiores iure vel. Corrupti similique beatae commodi quibusdam autem.',7,5);
INSERT INTO "app_evento" ( nombre, fecha_inicio, fecha_fin, descripcion, lugar_id, tematica_id) VALUES ('Intervenciones Urbanas','2024-11-01','2024-11-07','Numquam tempore blanditiis quos inventore vel. Atque velit illo voluptas illo. Harum iusto ad accusamus repellendus.',5,3);
INSERT INTO "app_evento" ( nombre, fecha_inicio, fecha_fin, descripcion, lugar_id, tematica_id) VALUES ('Espectáculos de Música en Vivo','2024-11-01','2024-11-07','Est eligendi aut nihil. Quod dignissimos quisquam quia modi nemo.',4,10);
INSERT INTO "app_evento" ( nombre, fecha_inicio, fecha_fin, descripcion, lugar_id, tematica_id) VALUES ('Proyecciones de Cine','2024-11-01','2024-11-07','Quos vitae nemo explicabo voluptas dolor asperiores. Adipisci praesentium corporis voluptatibus magnam quidem rerum. Distinctio iste minus veniam aliquam quisquam quae.',10,8);
INSERT INTO "app_evento" ( nombre, fecha_inicio, fecha_fin, descripcion, lugar_id, tematica_id) VALUES ('Premiación y Clausura','2024-11-01','2024-11-07','Molestiae necessitatibus eligendi dolore aliquid reprehenderit. Mollitia eligendi excepturi ipsam necessitatibus. Animi repudiandae quidem aspernatur facilis est neque.',7,4);
INSERT INTO "app_evento" ( nombre, fecha_inicio, fecha_fin, descripcion, lugar_id, tematica_id) VALUES ('Actividades para Niños','2024-11-01','2024-11-07','Odio ea ipsam. Facere reprehenderit id exercitationem est eos porro cupiditate. Odio nam est unde.',5,7);
INSERT INTO "app_evento" ( nombre, fecha_inicio, fecha_fin, descripcion, lugar_id, tematica_id) VALUES ('Artistas Invitados Internacionales','2024-11-01','2024-11-07','Placeat eius cumque quo eum. Quibusdam ullam ullam accusantium atque consequuntur.',7,1);
INSERT INTO "app_evento" ( nombre, fecha_inicio, fecha_fin, descripcion, lugar_id, tematica_id) VALUES ('Feria de Artesanía y Productos Locales','2024-11-01','2024-11-07','Rerum fugiat qui omnis. Vitae necessitatibus assumenda provident nulla tempore deserunt. Omnis quis facilis accusamus adipisci sapiente ab quibusdam.',2,11);
INSERT INTO "app_evento" ( nombre, fecha_inicio, fecha_fin, descripcion, lugar_id, tematica_id) VALUES ('Performance en Vivo','2024-11-01','2024-11-07','Corporis eum eius voluptatum voluptate. Repellat laudantium quae iste adipisci. Nisi id incidunt commodi dolor eaque velit officiis. Accusamus deserunt laborum adipisci.',10,13);
INSERT INTO "app_evento" ( nombre, fecha_inicio, fecha_fin, descripcion, lugar_id, tematica_id) VALUES ('Festival Gastronómico','2024-11-01','2024-11-07','Aliquid molestias quod molestias dolorum quod quos. Asperiores sapiente praesentium ullam asperiores quaerat. Ullam nobis sed impedit.',10,4);
INSERT INTO "app_evento" ( nombre, fecha_inicio, fecha_fin, descripcion, lugar_id, tematica_id) VALUES ('Exhibiciones de Realidad Virtual','2024-11-01','2024-11-07','Consectetur repellendus quo voluptatum quos. Velit accusamus dignissimos sequi non vel fuga non. Ullam optio doloribus reiciendis. Sit debitis laboriosam nam.',10,13);

-- ESCULTURA EVENTO
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (1,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (2,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (3,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (4,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (5,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (6,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (7,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (8,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (9,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (10,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (11,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (12,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (13,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (14,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (15,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (16,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (17,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (18,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (19,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (20,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (21,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (22,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (23,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (24,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (25,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (26,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (27,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (28,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (29,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (30,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (31,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (32,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (33,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (34,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (35,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (36,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (37,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (38,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (39,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (40,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (41,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (42,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (43,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (44,1);
INSERT INTO "app_escultorevento" ( escultor_id, evento_id) VALUES (45,1);




-- ESCULTURAS
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Ecos del Tiempo','Quibusdam saepe veritatis totam libero cum adipisci excepturi. Fugit nostrum cumque minus vel fugiat. Quas maxime iste excepturi ad dolorem.',NULL,19,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Raíces de Hierro','Ratione quas autem ullam quia sed officiis alias. Sit sint praesentium esse facere possimus. Consequuntur in repellat eum accusantium rem ab.',NULL,21,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('El Vuelo del Espíritu','Temporibus praesentium id occaecati fuga. Occaecati culpa sapiente quis. In tempora perferendis nesciunt.',NULL,35,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Sombras en Piedra','Placeat et sequi necessitatibus vel consequuntur voluptates. Tempora asperiores illo a harum. Velit esse reiciendis quidem illo.',NULL,30,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Horizontes de Bronce','Ipsa eum placeat tempora architecto quam natus. Dolorum laboriosam tempore aperiam voluptates amet. Veniam quia labore consequatur sapiente. Quaerat quis fugit amet.',NULL,18,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Misterio del Mar','Ad earum in iure deleniti. Distinctio saepe perspiciatis voluptatibus. Amet minus suscipit et sed accusantium laudantium.',NULL,10,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Fragmentos del Alma','Exercitationem alias dolores pariatur. Non necessitatibus commodi eligendi pariatur aliquam. Est molestiae odit beatae sapiente aperiam temporibus.',NULL,33,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Piedra y Luz','Quisquam porro iusto quae. Aliquid odit beatae tenetur numquam corrupti.',NULL,17,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Danza de Sombras','Vero nihil dolorum occaecati ab. Itaque eius tempora cum possimus sint veritatis. Saepe corrupti natus. Cumque blanditiis earum vel facere numquam.',NULL,41,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Reflejos Eternos','Iste qui explicabo impedit voluptatem illum. Laborum ab possimus alias.',NULL,10,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Luz en el Caos','Dolorem quos repellat dolorum soluta repellendus veritatis. Magnam possimus illum explicabo.',NULL,24,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Alas de Libertad','Dignissimos qui laudantium quae eum sint nam. Quas ipsa quidem beatae sequi quisquam tenetur possimus. Autem nisi quas neque hic mollitia rem. Dolor commodi aspernatur id.',NULL,21,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Espejismo del Desierto','A consequuntur ipsa eligendi expedita minima amet rem. Eos cum omnis tempore placeat quidem vitae.',NULL,31,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Luz y Sombra','Et iste deleniti. Occaecati mollitia assumenda voluptate blanditiis magni. Dicta vero soluta culpa. Temporibus animi quod sunt quos eveniet odio at.',NULL,31,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Espirales del Viento','Sunt laboriosam animi aspernatur. Repudiandae facere dicta distinctio vero.',NULL,19,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Guardianes de la Noche','Similique placeat rem eveniet corporis laudantium pariatur. Cum minus fugit dolores at. Magni neque sint harum aut.',NULL,19,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Corazón de la Tierra','Nam reprehenderit esse tempora. Reiciendis possimus molestias unde.',NULL,30,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Fragmentos de Silencio','Sapiente facilis vero. Animi dolore deserunt optio fugit soluta.',NULL,20,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Olas de Acero','Odit impedit saepe reprehenderit sit. Explicabo quia nostrum eaque officiis reiciendis. Quis repellendus beatae et eaque illum repudiandae explicabo.',NULL,35,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Senderos de Fuego','Tempora necessitatibus fuga rem rerum dignissimos. Harum at impedit commodi corporis dicta quod.',NULL,43,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Resonancia Profunda','Ratione reprehenderit animi. Unde at eius dolorum illo.',NULL,38,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Caminos de Sal','Sunt veniam corrupti. Nihil dolore dolorem. Doloribus culpa aliquid ullam nostrum veritatis facere.',NULL,7,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Reflejo en la Tormenta','Odio recusandae dolorum velit odio doloribus aliquam. Eligendi neque nihil enim. Officia animi doloribus suscipit ipsa.',NULL,34,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Lágrimas de Cristal','Repudiandae harum magni quam enim velit facere. Ea beatae velit in aspernatur nobis aliquid. Voluptate voluptatibus nostrum alias eius perferendis.',NULL,28,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Gravedad y Vuelo','Sequi perferendis quaerat aliquam. Ratione accusamus sed sed accusamus.',NULL,35,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Sombras del Horizonte','Dolor doloremque id dignissimos quidem magni sint. Nobis dolores saepe nobis esse. Culpa veritatis odio veniam.',NULL,16,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Alma de Fuego','Praesentium maxime aperiam ad hic inventore recusandae. Eveniet qui repellat eaque earum possimus. Distinctio ipsa doloribus saepe cum voluptatum.',NULL,35,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Bruma Matinal','Veniam error voluptatibus magnam ipsa quo cum. Fuga incidunt ipsa in saepe incidunt accusamus doloremque. Neque laudantium ipsum enim saepe.',NULL,4,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Cantos del Bosque','Ut aperiam perferendis consectetur dolor. Amet doloribus tenetur expedita. Hic sit quibusdam quos ut.',NULL,12,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Silencio de Roca','Consequatur repellat inventore nam odio consequuntur repudiandae magni. Ex corrupti magni occaecati amet aperiam.',NULL,20,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Viento en la Montaña','Itaque vel dignissimos laudantium.',NULL,35,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Fragilidad del Hielo','Nobis cupiditate eaque tempore sint nam. Beatae sit accusamus officia saepe odit maiores. Magni vel corrupti iste nostrum.',NULL,42,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Escala al Cielo','A aut vel rerum doloribus. Ea cumque accusamus distinctio dolore eos officia. Reiciendis dolorum ad unde voluptatem illo.',NULL,11,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Bosque Encantado','Rerum officiis corrupti. Repellat eligendi beatae illum distinctio. Ut quod incidunt ut nostrum. Voluptatum repudiandae asperiores ab ducimus cum harum.',NULL,33,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Abismo de Luz','Aut cumque vel sequi corporis.',NULL,25,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Raíces en el Cielo','Eligendi in architecto reiciendis tempore voluptate occaecati. Similique illum eum incidunt debitis provident voluptates ratione. Inventore recusandae enim quidem est distinctio sequi. Adipisci vitae amet quia maxime reiciendis fugiat dolor.',NULL,14,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Estelares del Tiempo','Deserunt aliquam sint error dicta reiciendis delectus. Velit nulla omnis consequatur nulla est. Deleniti ab numquam suscipit eius veniam in.',NULL,14,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Alquimia de Piedra','A dicta sequi reiciendis animi similique culpa. Corporis fugiat cupiditate iure blanditiis.',NULL,6,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Puentes de Sueño','A earum fugiat qui alias non aut. Pariatur explicabo similique.',NULL,24,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Fuente de Vida','Alias dolores illo ullam rerum nisi. Sequi officiis facere animi voluptate suscipit reprehenderit autem.',NULL,10,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Ecos de Hierro','Architecto provident sapiente modi cumque quisquam. Enim suscipit magnam vitae quas officiis.',NULL,28,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Fragmentos de Pasado','Error doloremque quaerat doloribus eaque eligendi. Eveniet ab architecto ducimus perferendis quam fugiat illum. Expedita tempore inventore quam fugit.',NULL,8,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Peregrino de la Luz','Eius ratione eaque minus aspernatur amet. Molestias illum nihil fugit minus velit. Cupiditate fugit quidem cumque id. Expedita nostrum quia reiciendis eos rerum quam.',NULL,9,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Voces de Agua','Accusamus aut impedit eius itaque consectetur iste. Unde animi ratione dicta.',NULL,16,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Río de Bronce','Impedit dolorem optio nemo ullam voluptate quo. Consequuntur placeat saepe perferendis doloribus dolor. Id sed eveniet sapiente excepturi.',NULL,43,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Silencio de Arena','Quod temporibus nemo maxime. Magni natus unde praesentium.',NULL,8,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Hijos del Amanecer','Accusamus id vel culpa. Laborum corporis minima doloribus nesciunt libero sequi porro. Dignissimos aperiam quasi pariatur nam.',NULL,35,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Sombras del Alba','Recusandae quae eius. Maiores enim laboriosam repellendus tenetur quae. Eveniet doloribus ullam cum tempora. Officia non reprehenderit explicabo fugiat unde.',NULL,10,'2024-11-01');
INSERT INTO "app_escultura" ( nombre, descripcion, qr, escultor_id, fecha_creacion) VALUES ('Ríos de Acero','Quam eligendi accusamus. Perspiciatis praesentium pariatur ipsam dolorem dolor fugiat. Corrupti aperiam eveniet.',NULL,2,'2024-11-01');

-- IMAGENES
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('119aGgfIkARhOkCmaUzqELzCaHeLA55ap','Id veritatis dicta nihil nihil. Necessitatibus eligendi quas repudiandae cupiditate explicabo ratione consectetur. Maiores eveniet facere facilis aliquid. Nostrum atque labore nulla veniam.',1,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('18dgAIoehWJSIDBgn808FQ8gntv9Nfqf7','Vitae minus quam repellat atque deleniti inventore. Laboriosam rem fuga aperiam. Id impedit magni impedit reprehenderit soluta omnis earum.',2,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1ApEtNxXBt7CGn6HyO3BQAji49Hd5TvIS','Possimus necessitatibus rem voluptatum. Voluptatibus eveniet eius eum maiores placeat repudiandae.',3,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1BH-8JBDRzFn_ximZgzK3SKbHAFjzMg3S','Earum magni similique facere quod explicabo. Esse veniam vero quas voluptatem quaerat quis. Praesentium facere nam eos eos debitis eligendi repudiandae. Maxime aliquam pariatur doloremque.',4,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1DGSrwSAOXZ96KLDFG47FqZvjI09Fr8a_','Delectus rerum laudantium ullam consectetur enim cupiditate. Ullam voluptatem neque distinctio non laudantium.',5,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1DoUezfPfrkklcjW9WXZTu6Y3Zs6fAPFA','Voluptatum quidem qui doloremque excepturi. Vero aspernatur consequatur cum.',6,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1EOKaZm0Du6V4gJZFc5gSIdag3h9XtPA6','Repellendus eum veritatis a voluptatum pariatur. Delectus aut ea facilis quis error a.',7,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1JQE1j8fOJ1AVjOOrTlleTqeNGtBYfA-z','Dolor nihil laborum culpa neque. Assumenda repudiandae eligendi assumenda. Enim velit odio harum est cum eum.',8,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1M_RtLVOM5GXp8kL4WXNjTUZOqBKZvYl9','Repudiandae nobis similique error sed tempora reprehenderit. Illum architecto magni aliquam veniam molestiae fugit ea. Eligendi cupiditate deleniti libero illo. Ex dolorum est tenetur.',9,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1RM_hoJTPwZ37aOoGeKqMmmI_CYq3I3Yy','Adipisci soluta hic quasi. Dignissimos velit voluptate incidunt dolorem ipsa cum eveniet.',10,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1Skt9_IiDWB3jbKEL5gzXRU7HK8D9AjVn','Ad ipsa id odio provident error laboriosam consectetur. Assumenda autem dolor illo laborum. Modi eum error repellendus nam omnis ab. Dicta modi dolorem necessitatibus recusandae cumque tenetur.',11,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1W6VRoYImLUic6ah8LuQO93BzmruLvZmn','Rem perspiciatis quibusdam fuga excepturi dignissimos.',12,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1__o0vQt41p7WnuA_Q5ywRWouxJWP5NOU','Inventore cumque nihil dolor illum rem eos consequuntur. Iusto blanditiis ipsa veniam.',13,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1hWorK2iyQAC2qnUoCOd3C7-iUX6YmoEO','Assumenda ipsam veritatis culpa debitis quidem. Odio enim quia debitis tempora adipisci.',14,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1iJXGUE38-Pz6WGxbw6KDN3qNXyC_XRBJ','Earum necessitatibus nesciunt ipsa. Sit quam ab explicabo molestiae. Delectus doloribus veniam beatae magni.',15,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1jMwagnmzkerVnXwsQPp7gNh0-kYK812E','Quis cum repellat iste.',16,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1kQfE7OGmXXnBATz4AfCMLui3tV8SJ2cE','A architecto quidem explicabo. Ab placeat ducimus quisquam repellat explicabo corrupti. Ut est cupiditate atque aspernatur sit.',17,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1obUqFO4S1BOUBpJDlzYaw8RbatjsoYgK','Sint excepturi illum.',18,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1rJFa_HnMm9SS3L9UmsKAAuDYab7upMIV','Eum expedita alias similique facere nam quo. Repellat libero ipsam optio nesciunt saepe explicabo. Nisi nisi quas eius architecto soluta.',19,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1sF0vkCf1xvoYnRw-xHiQ4Yteg9gNh1W4','Blanditiis ducimus ab excepturi unde nesciunt corrupti. Illo aliquid laboriosam non aperiam harum vel architecto. Quisquam consectetur perferendis eveniet ducimus et.',20,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1yy36Di7r_baXD9cmGwzeU7Cur_TcFrR2','Id sunt illo aut autem quia corporis. Perferendis dignissimos necessitatibus porro.',21,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1z6VteFD28kDWw_lsEJLcf6AxIdYezwBi','Quae possimus delectus dolor accusantium consequatur expedita. Vitae natus repellat a autem. Laboriosam et accusamus debitis exercitationem reiciendis.',22,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1-YqdsiB_7HTeMmclgWSayT-9J6a_uKOb','Culpa quaerat praesentium iste deserunt omnis alias laboriosam. Magnam quos magnam totam eligendi doloribus sunt aliquam.',23,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('16UTIkhPB_S5TiwcvLwySPhuFymYQxDFi','Enim doloribus nam sit expedita sapiente. Accusantium atque quibusdam dolores. Eligendi alias maiores ad quo ipsa.',24,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('17O7guY5C0Db9TZFRu4-3GvtXWaHkojJT','Suscipit sint ut laudantium error voluptatem.',25,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('18_UrjpB059l0oGoWyf6Ef9julSBsHIWa','Est ad blanditiis blanditiis fugit. Blanditiis quasi ex rerum eum sit corporis.',26,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1BS6bTZv7uYyr7hl48iBpjLRszZY7cVyM','Rem quaerat saepe cum quam aperiam ullam. Error dignissimos unde ipsa repellat quos delectus. Ad porro unde consectetur numquam perspiciatis qui.',27,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1C4F9MD6tF0iOxbiQB1nei49Yp7XSrQ4y','Officiis commodi incidunt blanditiis animi sed. Quam eaque nesciunt reiciendis.',28,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1C9n2_3WVHcaN_PCvK8TyNqZj3MgJ7apT','Itaque quisquam commodi tempora. Laborum debitis assumenda culpa illo laborum dicta voluptatem.',29,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1Dp8EC5DgTx_pAZAmn2sg_XNLP1sEVGoI','Enim molestias doloribus possimus tempore occaecati. Perspiciatis officia corporis.',30,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1Egob1Lg3BIK_XrfdaVfCnBT5ge-cIxP5','Pariatur mollitia consequuntur a consequuntur quae neque. In repudiandae non deserunt rerum non iste. Quia iure nemo modi quam nobis vitae rem.',31,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1FUH1lVAmzOLTEPs13_TUb7DdZu-96Us6','Pariatur porro eveniet unde sed sapiente facere molestiae. Ut consectetur quas incidunt. Molestiae suscipit distinctio assumenda praesentium non odit ipsam.',32,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1Ixct0w6f_RnDT6RGD1vx_MxmWkAwlNsF','Quos nihil atque deleniti. Fugiat aut quia minima. Necessitatibus est quisquam.',33,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1JTflFbuw8dUEqFaNlm3qm0uHHoIGa5CO','Molestiae earum deserunt accusamus unde similique dicta. Consequatur veritatis recusandae omnis alias natus.',34,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1N0bYCFPCgtFMMSNcZOqpYZgx90M6QZvR','Perspiciatis ducimus totam quam ipsum nulla delectus. Eveniet aliquid quam a dolorum. Dignissimos nesciunt quos similique expedita id.',35,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1PulV5W50S-06uiCuBSgJZm_9z2xfl9xN','Incidunt voluptatum impedit repellat dolor iste. Suscipit iure perspiciatis nesciunt amet delectus. Ratione excepturi error architecto illo voluptatem quaerat. Consectetur reprehenderit quibusdam laboriosam ut et dignissimos nulla.',36,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1WdhpTotUJAP0tuiDu11-HBYJ5RGwW1Lv','Ea iste excepturi harum laborum ex quos. Vero temporibus explicabo est ut.',37,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1_axpfGJGvnyExKE3Cwd8Ag643c4_eMcC','Eius soluta nihil inventore. Adipisci nam vero quaerat facere.',38,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1ehxioINe_J87TsSmzQW_BHV1T6_7_M3p','Quasi vel molestiae cupiditate. Incidunt possimus totam saepe fuga adipisci.',39,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1fYKlXyxwtcEV5RzqkcX9Stl2Ljvm_fYz','Veniam odit saepe unde. Harum minus ipsa cumque repellendus quam. Sequi excepturi vero optio totam fugit totam porro.',40,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1g6MlscH75HY0ThMQZEKkZ7qBp12uzNXS','Ut itaque repudiandae sed culpa illo saepe. Corporis est hic eius.',41,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1hD8rwXIGygrlh8QMHdtbarWResdH3bAC','Expedita cumque quos enim magnam eos. Corrupti voluptates ut maiores delectus. Quo voluptas commodi sint.',42,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1irWNLtYyMXkWWHrUvOfdE8lvp71dNveM','Porro fugiat quisquam nobis quisquam. Veniam suscipit id commodi perspiciatis vero harum.',43,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1mdc18oCCk9wmKC9Py_IA3kp9AAjGOvaz','Voluptatum veniam pariatur laboriosam. Impedit molestias neque ipsam. Et eligendi porro earum sequi.',44,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1nJL1SxWd6z3iBhd9l7tsthm0UJ6w_U07','Eaque expedita nesciunt nemo in deleniti voluptatem. Numquam voluptatibus at optio.',45,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1nV7tBmnC97rMQhR2RaU9HLP9W8Op45wP','Ipsam ab perspiciatis repudiandae. Quos tenetur corrupti. Ad quibusdam dolorum delectus enim quasi culpa.',46,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1q0UjymxJyeklZ9gMpGpJGcsPYJQYMj2C','Consequuntur itaque iure laborum. Distinctio sint praesentium consectetur voluptas repudiandae eligendi. Tempore earum minus libero occaecati officiis temporibus.',47,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1qq-31OCcocuZfuqrTVpd6HcI3n0Vl_2T','Sed quos cum. Quae consectetur corporis iure laboriosam.',48,'2024-11-01');
INSERT INTO "app_imagen" ( imagen, descripcion, escultura_id, fecha_creacion) VALUES ('1ur68yivDrhYPIVNTMNUGeckrho_il1UV','Quo sunt deserunt amet. Dolore dolore possimus quos placeat. Accusamus id hic amet beatae rem sequi. Placeat est deleniti corporis.',49,'2024-11-01');
