-- PAIS
INSERT INTO "app_pais" (nombre, iso) VALUES
('Afganistán','AF'),
('Islas Gland','AX'),
('Albania','AL'),
('Alemania','DE'),
('Andorra','AD'),
('Angola','AO'),
('Anguilla','AI'),
('Antártida','AQ'),
('Antigua y Barbuda','AG'),
('Antillas Holandesas','AN'),
('Arabia Saudí','SA'),
('Argelia','DZ'),
('Argentina','AR'),
('Armenia','AM'),
('Aruba','AW'),
('Australia','AU'),
('Austria','AT'),
('Azerbaiyán','AZ'),
('Bahamas','BS'),
('Bahréin','BH'),
('Bangladesh','BD'),
('Barbados','BB'),
('Bielorrusia','BY'),
('Bélgica','BE'),
('Belice','BZ'),
('Benin','BJ'),
('Bermudas','BM'),
('Bhután','BT'),
('Bolivia','BO'),
('Bosnia y Herzegovina','BA'),
('Botsuana','BW'),
('Isla Bouvet','BV'),
('Brasil','BR'),
('Brunéi','BN'),
('Bulgaria','BG'),
('Burkina Faso','BF'),
('Burundi','BI'),
('Cabo Verde','CV'),
('Islas Caimán','KY'),
('Camboya','KH'),
('Camerún','CM'),
('Canadá','CA'),
('República Centroafricana','CF'),
('Chad','TD'),
('República Checa','CZ'),
('Chile','CL'),
('China','CN'),
('Chipre','CY'),
('Isla de Navidad','CX'),
('Ciudad del Vaticano','VA'),
('Islas Cocos','CC'),
('Colombia','CO'),
('Comoras','KM'),
('República Democrática del Congo','CD'),
('Congo','CG'),
('Islas Cook','CK'),
('Corea del Norte','KP'),
('Corea del Sur','KR'),
('Costa de Marfil','CI'),
('Costa Rica','CR'),
('Croacia','HR'),
('Cuba','CU'),
('Dinamarca','DK'),
('Dominica','DM'),
('República Dominicana','DO'),
('Ecuador','EC'),
('Egipto','EG'),
('El Salvador','SV'),
('Emiratos Árabes Unidos','AE'),
('Eritrea','ER'),
('Eslovaquia','SK'),
('Eslovenia','SI'),
('España','ES'),
('Islas ultramarinas de Estados Unidos','UM'),
('Estados Unidos','US'),
('Estonia','EE'),
('Etiopía','ET'),
('Islas Feroe','FO'),
('Filipinas','PH'),
('Finlandia','FI'),
('Fiyi','FJ'),
('Francia','FR'),
('Gabón','GA'),
('Gambia','GM'),
('Georgia','GE'),
('Islas Georgias del Sur y Sandwich del Sur','GS'),
('Ghana','GH'),
('Gibraltar','GI'),
('Granada','GD'),
('Grecia','GR'),
('Groenlandia','GL'),
('Guadalupe','GP'),
('Guam','GU'),
('Guatemala','GT'),
('Guayana Francesa','GF'),
('Guinea','GN'),
('Guinea Ecuatorial','GQ'),
('Guinea-Bissau','GW'),
('Guyana','GY'),
('Haití','HT'),
('Islas Heard y McDonald','HM'),
('Honduras','HN'),
('Hong Kong','HK'),
('Hungría','HU'),
('India','IN'),
('Indonesia','ID'),
('Irán','IR'),
('Iraq','IQ'),
('Irlanda','IE'),
('Islandia','IS'),
('Israel','IL'),
('Italia','IT'),
('Jamaica','JM'),
('Japón','JP'),
('Jordania','JO'),
('Kazajstán','KZ'),
('Kenia','KE'),
('Kirguistán','KG'),
('Kiribati','KI'),
('Kuwait','KW'),
('Laos','LA'),
('Lesotho','LS'),
('Letonia','LV'),
('Líbano','LB'),
('Liberia','LR'),
('Libia','LY'),
('Liechtenstein','LI'),
('Lituania','LT'),
('Luxemburgo','LU'),
('Macao','MO'),
('ARY Macedonia','MK'),
('Madagascar','MG'),
('Malasia','MY'),
('Malawi','MW'),
('Maldivas','MV'),
('Malí','ML'),
('Malta','MT'),
('Islas Malvinas','FK'),
('Islas Marianas del Norte','MP'),
('Marruecos','MA'),
('Islas Marshall','MH'),
('Martinica','MQ'),
('Mauricio','MU'),
('Mauritania','MR'),
('Mayotte','YT'),
('México','MX'),
('Micronesia','FM'),
('Moldavia','MD'),
('Mónaco','MC'),
('Mongolia','MN'),
('Montserrat','MS'),
('Mozambique','MZ'),
('Myanmar','MM'),
('Namibia','NA'),
('Nauru','NR'),
('Nepal','NP'),
('Nicaragua','NI'),
('Níger','NE'),
('Nigeria','NG'),
('Niue','NU'),
('Isla Norfolk','NF'),
('Noruega','NO'),
('Nueva Caledonia','NC'),
('Nueva Zelanda','NZ'),
('Omán','OM'),
('Países Bajos','NL'),
('Pakistán','PK'),
('Palau','PW'),
('Palestina','PS'),
('Panamá','PA'),
('Papúa Nueva Guinea','PG'),
('Paraguay','PY'),
('Perú','PE'),
('Islas Pitcairn','PN'),
('Polinesia Francesa','PF'),
('Polonia','PL'),
('Portugal','PT'),
('Puerto Rico','PR'),
('Qatar','QA'),
('Reino Unido','GB'),
('Reunión','RE'),
('Ruanda','RW'),
('Rumania','RO'),
('Rusia','RU'),
('Sahara Occidental','EH'),
('Islas Salomón','SB'),
('Samoa','WS'),
('Samoa Americana','AS'),
('San Cristóbal y Nevis','KN'),
('San Marino','SM'),
('San Pedro y Miquelón','PM'),
('San Vicente y las Granadinas','VC'),
('Santa Helena','SH'),
('Santa Lucía','LC'),
('Santo Tomé y Príncipe','ST'),
('Senegal','SN'),
('Serbia y Montenegro','CS'),
('Seychelles','SC'),
('Sierra Leona','SL'),
('Singapur','SG'),
('Siria','SY'),
('Somalia','SO'),
('Sri Lanka','LK'),
('Suazilandia','SZ'),
('Sudáfrica','ZA'),
('Sudán','SD'),
('Suecia','SE'),
('Suiza','CH'),
('Surinam','SR'),
('Svalbard y Jan Mayen','SJ'),
('Tailandia','TH'),
('Taiwán','TW'),
('Tanzania','TZ'),
('Tayikistán','TJ'),
('Territorio Británico del Océano Índico','IO'),
('Territorios Australes Franceses','TF'),
('Timor Oriental','TL'),
('Togo','TG'), 
('Tokelau','TK'),
('Tonga','TO'),
('Trinidad y Tobago','TT'),
('Túnez','TN'),
('Islas Turcas y Caicos','TC'),
('Turkmenistán','TM'),
('Turquía','TR'),
('Tuvalu','TV'),
('Ucrania','UA'),
('Uganda','UG'),
('Uruguay','UY'),
('Uzbekistán','UZ'),
('Vanuatu','VU'),
('Venezuela','VE'),
('Vietnam','VN'),
('Islas Vírgenes Británicas','VG'),
('Islas Vírgenes de los Estados Unidos','VI'),
('Wallis y Futuna','WF'),
('Yemen','YE'),
('Yibuti','DJ'),
('Zambia','ZM'),
('Zimbabue','ZW');

-- APP LUGAR
INSERT INTO "app_lugar" (nombre, descripcion) VALUES 
('Zona Automotrices', 'Espacio destinado a la exposición y venta de vehículos y productos relacionados con la industria automotriz, incluyendo repuestos y accesorios.'),
('Zona Artesanos', 'Área donde se exhiben y comercializan productos hechos a mano, como artesanías en madera, cerámica, textiles y otros materiales.'),
('Zona Emprendedores', 'Sector destinado a pequeñas empresas y startups para promocionar y vender sus productos o servicios innovadores.'),
('Zona Cancha de basket', 'Espacio deportivo equipado para la práctica de básquetbol, disponible tanto para partidos oficiales como para actividades recreativas.'),
('Zona Cancha de voley', 'Área habilitada para el juego de vóleibol, diseñada con las medidas reglamentarias y equipada para torneos o prácticas.'),
('Zona Gastronomías', 'Lugar dedicado a la venta de comidas y bebidas, con stands y food trucks que ofrecen una variedad de opciones culinarias.'),
('Zona Pymes', 'Espacio de exposición para pequeñas y medianas empresas, donde pueden presentar sus productos, servicios y proyectos.'),
('Zona Prensa', 'Área reservada para periodistas y medios de comunicación, equipada con mesas, puntos de conexión y acceso a información del evento.'),
('Zona Pista de atletismo', 'Circuito diseñado para actividades atléticas como carreras y competencias, con superficie reglamentaria y señalización adecuada.'),
('Zona Puestos de Salud', 'Sector dedicado a la atención médica básica, con puestos de primeros auxilios y personal capacitado para emergencias.');


-- APP TEMATICA
INSERT INTO "app_tematica" (nombre, descripcion) VALUES
('Naturaleza y Paisaje', 'Exploración de la belleza natural y los paisajes, destacando la conexión entre los seres humanos y el medio ambiente.'),
('Identidad Cultural', 'Reflexión sobre las tradiciones, costumbres y diversidad cultural que definen a diferentes comunidades.'),
('Tecnología y Futuro', 'Análisis de los avances tecnológicos y su impacto en el futuro de la sociedad y la cultura.'),
('Memoria Histórica', 'Preservación y reconocimiento de los eventos y figuras clave que han moldeado nuestra historia.'),
('Abstracción y Color', 'Exploración de formas abstractas y el uso del color como medio de expresión artística.'),
('Diversidad y Género', 'Celebración de la diversidad y promoción de la equidad de género en todas sus formas.'),
('Ecología y Sustentabilidad', 'Concienciación sobre la importancia del cuidado del medio ambiente y el desarrollo sostenible.'),
('Exploración Espacial', 'Reflexión sobre los descubrimientos y posibilidades del universo más allá de nuestro planeta.'),
('Misticismo y Religión', 'Estudio de las creencias espirituales, religiosas y místicas de diferentes culturas.'),
('Migración y Fronteras', 'Representación de las experiencias de migrantes y los desafíos asociados con las fronteras.'),
('Arte y Ciencia', 'Intersección entre la creatividad artística y los avances científicos para explorar nuevas perspectivas.'),
('Sueños y Realidad', 'Representación artística de la dualidad entre el mundo onírico y la vida cotidiana.'),
('Tiempo y Espacio', 'Exploración de conceptos abstractos relacionados con el tiempo y el espacio, y su impacto en nuestra percepción.'),
('El Cuerpo Humano', 'Estudio del cuerpo humano como tema artístico, explorando su belleza, funcionalidad y complejidad.'),
('Emociones y Expresiones', 'Interpretación artística de las emociones humanas y las formas de expresarlas a través del arte.');


-- APP EVENTO
INSERT INTO "app_evento" (nombre, fecha_inicio, fecha_fin, descripcion, lugar_id, foto, tematica_id, finalizado) VALUES
('Concurso Internacional de Escultura - 2025', '2025-11-01', '2025-11-07', 'Evento, en su edición 2025, en el que escultores de todo el mundo competirán mostrando su creatividad y técnicas únicas, con premios para las mejores obras.', 5, 'img/eventos/ConcursoInternacionalDeEsculturas.webp', 6, True),
('Concurso Internacional de Escultura - 2022', '2022-11-01', '2022-11-07', 'Evento, en su edición 2022, en el que escultores de todo el mundo competirán mostrando su creatividad y técnicas únicas, con premios para las mejores obras.', 7, 'img/eventos/ExposicionesDeArte.webp', 6, True),
('Exposiciones de Arte', '2024-11-01', '2024-11-07', 'Muestra de obras de arte en diferentes estilos y técnicas, desde pintura hasta fotografía, abiertas al público durante toda la semana.', 10, 'img/eventos/ConcursoInternacionalDeEsculturas.webp', 13, True),
('Talleres y Capacitaciones', '2024-11-01', '2024-11-07', 'Espacios interactivos donde los asistentes podrán aprender nuevas habilidades en áreas como diseño, tecnología y artes.', 1,'img/eventos/TalleresYCapacitacion.webp', 12, True),
('Conferencias y Charlas', '2024-11-01', '2024-11-07', 'Presentaciones de expertos en diversos temas, desde innovación hasta desarrollo personal, abiertas al público.', 3, 'img/eventos/ConferenciasYcharlas.webp', 2, True),
('Recorridos Guiados', '2024-11-01', '2024-11-07', 'Visitas organizadas para explorar áreas destacadas del evento, con guías expertos que brindarán información detallada.', 7, 'img/eventos/RecorridosGuiado.webp', 5, True),
('Intervenciones Urbanas', '2024-11-01', '2024-11-07', 'Proyectos artísticos que transforman espacios públicos a través de instalaciones creativas e interactivas.', 5, 'img/eventos/IntervencionesUrbanas.webp', 3, True),
('Espectáculos de Música en Vivo', '2024-11-01', '2024-11-07', 'Conciertos de bandas y artistas locales e internacionales, con un ambiente vibrante y diverso.', 4, 'img/eventos/EspectáculosMusicaEnVivo.webp', 10, True),
('Proyecciones de Cine', '2024-11-01', '2024-11-07', 'Proyección de películas clásicas y contemporáneas, con énfasis en producciones independientes y de autor.', 10, 'img/eventos/ProyeccionesDeCine.webp', 8, True),
('Premiación y Clausura', '2024-11-01', '2024-11-07', 'Ceremonia de cierre del evento con entrega de premios y reconocimientos a participantes destacados.', 7, 'img/eventos/PremiaciónyClausura.webp', 4, True),
('Actividades para Niños', '2024-11-01', '2024-11-07', 'Zona interactiva con juegos, talleres y actividades recreativas diseñadas especialmente para los más pequeños.', 5, 'img/eventos/ActividadesParaNiños.webp', 7, True),
('Artistas Invitados Internacionales', '2024-11-01', '2024-11-07', 'Participación especial de artistas de renombre mundial que compartirán su trabajo y experiencias.', 7, 'img/eventos/ArtistasInvitadosInternacionales.webp', 1, True),
('Feria de Artesanía y Productos Locales', '2024-11-01', '2024-11-07', 'Exhibición y venta de artesanías, alimentos y productos elaborados por productores locales.', 2, 'img/eventos/FeriaDeArtesania.webp', 11, True),
('Performance en Vivo', '2024-11-01', '2024-11-07', 'Espectáculos teatrales y de danza contemporánea, realizados por compañías y artistas independientes.', 10,' img/eventos/PerformanceEnVivo.webp', 13, True),
('Festival Gastronómico', '2024-11-01', '2024-11-07', 'Encuentro culinario donde los asistentes podrán degustar una amplia variedad de platillos de diferentes culturas.', 10, 'img/eventos/FestivalGastronomico.webp', 4, True),
('Exhibiciones de Realidad Virtual', '2024-11-01', '2024-11-07', 'Demostraciones interactivas de tecnología de realidad virtual, con experiencias inmersivas para los asistentes.', 10, 'img/eventos/ExhibicionesDeRealidadVirtual.webp', 13, True);

-- APP ESCULTORES
INSERT INTO "app_escultor" (correo, bibliografia, pais_id, fecha_nacimiento, nombre, apellido, foto) VALUES
('sarita.collado@example.org', 'Escultora especializada en figuras abstractas con un enfoque en formas geométricas y colores vivos.', 77, '2004-10-11', 'Sarita', 'Collado', 'img/perfiles/sarita.webp'),
('juan.nebot@example.net', 'Reconocido por sus esculturas en mármol, reflejando la cultura mediterránea.', 13, '1993-04-27', 'Juan Carlos', 'Nebot', 'img/perfiles/juanCarlos.webp'),
('ramiro.lopez@example.org', 'Escultor innovador que trabaja con técnicas digitales para crear piezas futuristas.', 98, '1989-08-14', 'Ramiro', 'López', 'img/perfiles/ramiro.webp'),
('xavier.comas@example.org', 'Especialista en esculturas minimalistas que exploran el equilibrio y la simplicidad.', 184, '2006-01-22', 'Xavier', 'Comas', 'img/perfiles/xavier.webp'),
('duilio.roda@example.com', 'Famoso por sus esculturas monumentales en espacios públicos que resaltan la identidad cultural local.', 216, '1999-12-22', 'Duilio', 'Roda', 'img/perfiles/dulio.webp'),
('maricruz.blazquez@example.com', 'Creadora de esculturas figurativas con un estilo detallado y emocional.', 75, '1999-02-24', 'Maricruz', 'Blázquez', 'img/perfiles/maricruz.webp'),
('buenaventura.lerma@example.org', 'Conocido por su trabajo en bronce, sus obras reflejan la naturaleza humana y sus emociones.', 154, '1988-03-05', 'Buenaventura', 'Lerma', 'img/perfiles/buenaventura.webp'),
('fernando.sierra@example.com', 'Escultor emergente con un enfoque en materiales orgánicos como madera y piedra.', 232, '2005-09-15', 'Fernando', 'Sierra', 'img/perfiles/fernando.webp'),
('florentino.espinosa@example.com', 'Artista autodidacta que utiliza técnicas mixtas para crear esculturas con movimiento.', 29, '1981-02-22', 'Florentino', 'Espinosa', 'img/perfiles/florentino.webp'),
('roberta.galvan@example.org', 'Sus esculturas en cerámica exploran temas de feminidad y naturaleza.', 172, '1990-11-12', 'Roberta', 'Galván', 'img/perfiles/roberta.webp'),
('rodolfo.gimeno@example.net', 'Escultor especializado en obras de gran escala para instalaciones urbanas.', 146, '2006-01-24', 'Rodolfo', 'Gimeno', 'img/perfiles/rodolfo.webp'),
('noelia.nunez@example.com', 'Escultora joven conocida por su habilidad para transformar materiales industriales en arte.', 173, '1997-03-01', 'Noelia', 'Núñez', 'img/perfiles/noelia.webp'),
('tito.rocha@example.org', 'Su obra combina elementos históricos con técnicas modernas, creando piezas únicas.', 46, '1984-06-29', 'Tito', 'Rocha', 'img/perfiles/tito.webp'),
('clotilde.valenzuela@example.org', 'Escultora abstracta que experimenta con materiales reciclados para promover la sostenibilidad.', 13, '2003-09-11', 'Clotilde', 'Valenzuela', 'img/perfiles/clotilde.webp'),
('cayetana.porta@example.org', 'Sus esculturas de vidrio destacan por su delicadeza y atención al detalle.', 73, '1986-06-29', 'Cayetana', 'Porta', 'img/perfiles/cayetana.webp'),
('socorro.armengol@example.com', 'Conocida por sus esculturas que integran tecnología y arte, explorando el movimiento y la luz.', 58, '1995-06-17', 'Socorro', 'Armengol', 'img/perfiles/socorro.webp'),
('lidia.perez@example.net', 'Artista multidisciplinaria con un enfoque en esculturas interactivas.', 112, '1991-04-23', 'Lidia', 'Pérez', 'img/perfiles/lidia.webp'),
('casandra.isern@example.org', 'Artista contemporánea que trabaja con materiales reciclados para crear piezas innovadoras.', 129, '1988-09-19', 'Casandra', 'Isern', 'img/perfiles/casandra.webp');


-- ESCULTOR EVENTO
INSERT INTO "app_escultorevento" (escultor_id, evento_id) VALUES
(1,1),
(2,1),
(3,1),
(4,1),
(5,1),
(6,1),
(7,1),
(8,1),
(9,1),
(10,2),
(11,2),
(12,2),
(13,2),
(14,2),
(15,2),
(16,2),
(17,2),
(18,2);

-- app escultura
INSERT INTO "app_escultura" (nombre, descripcion, escultor_id, fecha_creacion) VALUES 
('Tiempo', 'El concepto de tiempo es una bola de enigmas inconscientes que suponen un desafío para recordar. Se puede clasificar en físico, biológico y físico subjetivo. La realidad más distinta es el tiempo físico, que está ligado al espacio y forma un espacio-tiempo curvo que continúa expandiéndose continuamente. El tiempo biológico es cíclicamente rítmico y todo organismo vivo lo tiene, está predestinado. El tiempo psíquico subjetivo es idéntico a la autoconciencia humana regida por la relación de incertidumbre de la física cuántica. Por lo tanto, su naturaleza ondulante no se presta a una inspección localizada. El tiempo cuando trato de representarlo en forma visual y en forma de posibilidades materiales.', 1, '2025-07-01'),
('Multiplicidad', 'La escultura busca, a través de su construcción -en base a planos triangulares, el color, su recorrido de luz y sombra-, producir distintas percepciones espaciales. Es decir; a medida que la recorremos y la miramos desde distintos ángulos podemos ver que se van generando distintas figuras geométricas que se producen por la proyección de sus líneas y sombras, configurando a través del vacío, volúmenes virtuales que nos sugieren una multiplicidad de formas y distintas perspectivas sobre la misma obra. La escultura proyectada está pensada para ser recorrida y poder apreciar desde la mayor cantidad de vistas, la construcción de volúmenes en base a planos y vacíos, teniendo la oportunidad de poder situarse en el interior de la obra y tener una nueva experiencia espacial. La escultura busca hacer tangible la idea de que somos parte de un todo, que se conforma desde múltiples perspectivas, miradas, posiciones, y cada una de ella es válida y necesaria para conformar un todo. Con esta obra se quiere hacer una representación abstracta de la diversidad de individuos que habitamos y compartimos un mismo espacio, pero al mismo tiempo muy diverso, en el cual convergen una infinidad de posibilidades en el habitar, dándonos cuenta que a partir de la individualidad de formas se puede generar un todo dentro de una multidimensional, habitando un sub-espacio que nos convierte en uno y en todo.', 2, '2025-07-01'),
('Habitus, antihabitus', 'Esta pieza esculpida en hierro ancla su nacimiento y construcción a partir de la papiroflexia y el origami. En la práctica de cortar y doblar papel moldeo volúmenes y escalo perspectivas elevando el plano. Esta naturaleza flexible a la que me invita este material y sus infinitas posibilidades de plegado me permiten concebir estas ideas. A pesar que el papel es un objeto bidimensional, con el corte y el plegado se consigue visualizar y entender cómo la escultura comienza a habitar el espacio a través de ángulos, luces y sombras. De esta manera consigo abrir sutiles vías de exploración a través de ritmos internos y movimientos centrífugos. Hay cuatro puntos que considero clave en el desarrollo de esta pieza para garantizar la precisión, la coherencia y la belleza: el rigor matemático, la repetición con diferencias, el movimiento congelado a través de tensiones y líneas cinéticas y la idea conceptual de habitar y ser habitada. Habitus, antihabitus surge por la importancia que tiene el vacío en mi obra, habla del camino recorrido entre las dos piezas hasta encontrarse y abrazarse. Representa la unión y la armonía entre diferentes culturas, tradiciones y perspectivas. Representa la conexión ineludible entre el pasado y el presente. La tradición de unos valores porque se repiten y que se repiten porque son valores. Y es que la vida no permanece invariable. Habitus es lo tenido, lo habido, lo poseído pero también es lo que es recibido, lo que es tratado y recibido tal como ha sido tratado. Es aquello que permite al individuo y al grupo perseverar en su ser. Antihabitus es cambiar siempre, rechazar el hábito para no vivir inconscientemente la vida de otra cosa, de otro tiempo, de otra persona, de otra estructura, para que yo no use de modo inconsciente otro lenguaje, para que yo me apodere de mi propio lenguaje. Siempre es necesario pensar de otro modo, y es necesario hacerlo, aunque sea para después volver al modo anterior pero desde otro ángulo.', 3, '2025-07-01'),
('Reflejo de la luna', 'El punto de partida de esta escultura es el reflejo de la luna en la superficie del agua. Una síntesis tridimensional entre línea curva y volumen, lleno y vacío, reflejo instantáneo y material metálico. La escultura se compone de tres elementos cuyos volúmenes convergen entre sí, como los elementos de un rompecabezas que se pueden poner en relación en infinidad de composiciones. La obra es esencialmente la belleza del espejismo Fata Morgana capturado en volumen, modelando la línea vibrante entre la luz y la sombra.', 4, '2025-07-01'),
('Ritmo cósmico', 'Formas geométricas desplegadas en el espacio siguiendo un orden numérico, como imagen del orden del cosmos; así, la unidad de lo primigenio, la dualidad de nuestra polaridad emocional, la triada que nos reintegra a la unidad. Expansión y contracción visual al recorrer los 360 grados, a modo de respiración rítmica. Pliegue y despliegue de planos. El color rojo en su valor simbólico de amor universal, pasión y vitalidad. Una aspiración de lo material hacia lo espiritual. Los seres humanos somos imagen del orden cósmico. Cuando perdemos nuestra esencia surgen el caos y el desastre de la destrucción de nuestra humanidad, que llevan a la confrontación de pueblo contra pueblo. Cuando podemos recuperar el sentido rítmico nos podemos reintegrar como humanidad, hermanada en la danza del cosmos. Por eso, que las formas que en el cielo dibujan los astros, vibren hoy en nuestras manos; que la fuerza de las formas geométricas, resuene hoy en nuestro corazón; que el brillo de la luz, modele la forma celestial.', 5, '2025-07-01'),
('Mensaje', 'Una obra sobre el paisaje onírico. Toma la forma abstracta surrealista de un dardo de papel y recuerda al espectador un sentimiento de infancia. Recuerda la sensación de soñar y enviarla como un deseo. La obra utiliza el símbolo del dardo de papel y que recuerda el juego infantil de intentar volar un avión de papel lo más lejos que puedas. Se trata de volar, de esperar y de enviar un deseo a tu yo futuro como la proyección de un sueño. Quizás sea un lugar al que desea viajar, una persona que desea ver… es algo que el espectador debe imaginar. La superficie está facetada, lo que para mí representa algo mágico y alejado de la normalidad de la vida cotidiana.', 6, '2025-07-01'),
('Abstracto figurativo', 'Mi proyecto representa el cuerpo de una mujer de una manera muy sencilla. La idea es decir que la belleza está dentro del carácter de una persona, no sólo en la vista exterior o en la forma del cuerpo. Hay algunas virtudes que caracterizan a una persona: sabiduría, justicia, prudencia, moralidad, etc.', 7, '2025-07-01'),
('Escapar', 'Mi trabajo se ubica en una linealidad entre materia y representación (el cuerpo humano). Los contrastes entre material y representación están en el centro de mi proceso de producción. En mi práctica de producción, el material siempre habla por sí solo. El trabajo está organizado para revelar este proceso. Esto es posible a través de la reconciliación y el diálogo con la materia. Lo importante en este punto es que el material hable. La forma final la dejo al material. En mi diálogo con el material, lo que encuentro en cada paso prepara el terreno para el siguiente. Esta experiencia entre el artista y el material avanza en capas y llega a su conclusión. La forma del cuerpo se manifiesta en un estado de tensión con la materia. Este proyecto hace referencia a la dificultad y temporalidad del acto humano de escapar de un fenómeno.', 8, '2025-07-01'),
('Obelisco', 'El elemento principal de la escultura abstracta que no se suele discutir es el espíritu y el sentimiento de la obra, principalmente porque la gente quiere saber qué es más que la idea básica de disfrutar de su experiencia. Los elementos escultóricos abstractos suelen ser irreconocibles en el mundo real, ya que se toman libertades en el tema simplemente porque la copia es inadecuada y limitada para la expresión. Desde la antigüedad, el arte se ha centrado más en la expresión individual del objeto, la persona y el lugar, en lugar de simplemente replicar lo que hay allí. La escultura abstracta es la síntesis de ideas, pensamientos y lenguaje visual. La culminación de estos aspectos se refina a una esencia de simplicidad que expresa el sentimiento y el espíritu del sujeto en lugar de replicarlo. Hay características en la escultura abstracta que le confieren su unicidad y atractivo. Estas características son una separación completa del mundo natural.', 9, '2025-07-01'),
('Horizonte Eterno', 'Una obra que captura la sensación de infinitud del horizonte, combinando líneas horizontales y formas curvas que evocan la conexión entre el cielo y la tierra. Inspirada en paisajes naturales y su eternidad visual.', 10, '2022-07-01'),
('Fragmentos del Alma', 'Esta escultura combina elementos abstractos y figurativos para representar los fragmentos que componen el alma humana. Cada pieza refleja emociones como alegría, tristeza y esperanza.', 11, '2022-07-01'),
('Geometría del Silencio', 'Un tributo a la paz y la introspección, la obra utiliza formas geométricas simples y un diseño minimalista para transmitir calma y serenidad.', 12, '2022-07-01'),
('Raíces de la Historia', 'Representación de cómo las raíces culturales conectan a las generaciones. La escultura está hecha de madera reciclada, simbolizando la preservación del pasado.', 13, '2022-07-01'),
('Sombras de Luz', 'Explora la interacción entre sombra y luz en formas abstractas. Las superficies irregulares de la obra crean un juego visual constante a medida que la luz cambia.', 14, '2022-07-01'),
('Viento Esculpido', 'Una interpretación artística del viento, esta escultura utiliza líneas fluidas y formas onduladas para capturar la esencia del movimiento del aire.', 15, '2022-07-01'),
('Ecos del Futuro', 'Una obra futurista que utiliza materiales metálicos reciclados para simbolizar la conexión entre la tecnología y el medio ambiente.', 16, '2022-07-01'),
('La Danza del Cosmos', 'Inspirada en los movimientos de los cuerpos celestes, esta escultura representa la armonía universal a través de formas circulares entrelazadas.', 17, '2022-07-01'),
('El Rostro del Tiempo', 'Una obra que combina formas abstractas para simbolizar las capas del tiempo y su impacto en la humanidad, desde la historia hasta el futuro.', 18, '2022-07-01');


-- APP IMAGEN
INSERT INTO "app_imagen" (fecha_creacion, escultura_id, imagen) VALUES
	 ('2024-11-26', 1, 'img/esculturas/sarita-1.webp'),
	 ('2024-11-26', 1, 'img/esculturas/sarita-2.webp'),
	 ('2024-11-26', 1, 'img/esculturas/sarita-3.webp'),
	 ('2024-11-26', 1, 'img/esculturas/sarita-4.webp'),
	 ('2024-11-26', 1, 'img/esculturas/sarita-5.webp'),
	 ('2024-11-26', 1, 'img/esculturas/sarita-6.webp'),
	 ('2024-11-26', 1, 'img/esculturas/sarita-7.webp'),
	 ('2024-11-26', 1, 'img/esculturas/sarita-8.webp'),
	 ('2024-11-26', 1, 'img/esculturas/sarita-9.webp'),
	 ('2024-11-26', 2, 'img/esculturas/juanCarlos-1.webp'),
	 ('2024-11-26', 2, 'img/esculturas/juanCarlos-2.webp'),
	 ('2024-11-26', 2, 'img/esculturas/juanCarlos-3.webp'),
	 ('2024-11-26', 2, 'img/esculturas/juanCarlos-4.webp'),
	 ('2024-11-26', 2, 'img/esculturas/juanCarlos-5.webp'),
	 ('2024-11-26', 2, 'img/esculturas/juanCarlos-6.webp'),
	 ('2024-11-26', 2, 'img/esculturas/juanCarlos-7.webp'),
	 ('2024-11-26', 2, 'img/esculturas/juanCarlos-8.webp'),
	 ('2024-11-26', 2, 'img/esculturas/juanCarlos-9.webp'),
	 ('2024-11-26', 3, 'img/esculturas/ramiro-1.webp'),
	 ('2024-11-26', 3, 'img/esculturas/ramiro-2.webp'),
	 ('2024-11-26', 3, 'img/esculturas/ramiro-3.webp'),
	 ('2024-11-26', 3, 'img/esculturas/ramiro-4.webp'),
	 ('2024-11-26', 3, 'img/esculturas/ramiro-5.webp'),
	 ('2024-11-26', 3, 'img/esculturas/ramiro-6.webp'),
	 ('2024-11-26', 3, 'img/esculturas/ramiro-7.webp'),
	 ('2024-11-26', 3, 'img/esculturas/ramiro-8.webp'),
	 ('2024-11-26', 3, 'img/esculturas/ramiro-9.webp'),
	 ('2024-11-26', 4, 'img/esculturas/xavier-1.webp'),
	 ('2024-11-26', 4, 'img/esculturas/xavier-2.webp'),
	 ('2024-11-26', 4, 'img/esculturas/xavier-3.webp'),
	 ('2024-11-26', 4, 'img/esculturas/xavier-4.webp'),
	 ('2024-11-26', 4, 'img/esculturas/xavier-5.webp'),
	 ('2024-11-26', 4, 'img/esculturas/xavier-6.webp'),
	 ('2024-11-26', 4, 'img/esculturas/xavier-7.webp'),
	 ('2024-11-26', 4, 'img/esculturas/xavier-8.webp'),
	 ('2024-11-26', 4, 'img/esculturas/xavier-9.webp'),
	 ('2024-11-26', 5, 'img/esculturas/duilio-1.webp'),
	 ('2024-11-26', 5, 'img/esculturas/duilio-2.webp'),
	 ('2024-11-26', 5, 'img/esculturas/duilio-3.webp'),
	 ('2024-11-26', 5, 'img/esculturas/duilio-4.webp'),
	 ('2024-11-26', 5, 'img/esculturas/duilio-5.webp'),
	 ('2024-11-26', 5, 'img/esculturas/duilio-6.webp'),
	 ('2024-11-26', 5, 'img/esculturas/duilio-7.webp'),
	 ('2024-11-26', 5, 'img/esculturas/duilio-8.webp'),
	 ('2024-11-26', 5, 'img/esculturas/duilio-9.webp'),
	 ('2024-11-26', 6, 'img/esculturas/maricruz-1.webp'),
	 ('2024-11-26', 6, 'img/esculturas/maricruz-2.webp'),
	 ('2024-11-26', 6, 'img/esculturas/maricruz-3.webp'),
	 ('2024-11-26', 6, 'img/esculturas/maricruz-4.webp'),
	 ('2024-11-26', 6, 'img/esculturas/maricruz-5.webp'),
	 ('2024-11-26', 6, 'img/esculturas/maricruz-6.webp'),
	 ('2024-11-26', 6, 'img/esculturas/maricruz-7.webp'),
	 ('2024-11-26', 6, 'img/esculturas/maricruz-8.webp'),
	 ('2024-11-26', 6, 'img/esculturas/maricruz-9.webp'),
	 ('2024-11-26', 7, 'img/esculturas/buenaventura-1.webp'),
	 ('2024-11-26', 7, 'img/esculturas/buenaventura-2.webp'),
	 ('2024-11-26', 7, 'img/esculturas/buenaventura-3.webp'),
	 ('2024-11-26', 7, 'img/esculturas/buenaventura-4.webp'),
	 ('2024-11-26', 7, 'img/esculturas/buenaventura-5.webp'),
	 ('2024-11-26', 7, 'img/esculturas/buenaventura-6.webp'),
	 ('2024-11-26', 7, 'img/esculturas/buenaventura-7.webp'),
	 ('2024-11-26', 7, 'img/esculturas/buenaventura-8.webp'),
	 ('2024-11-26', 7, 'img/esculturas/img/esculturas/buenaventura-9.webp'),
	 ('2024-11-26', 8, 'img/esculturas/fernando-1.webp'),
	 ('2024-11-26', 8, 'img/esculturas/fernando-2.webp'),
	 ('2024-11-26', 8, 'img/esculturas/fernando-3.webp'),
	 ('2024-11-26', 8, 'img/esculturas/fernando-4.webp'),
	 ('2024-11-26', 8, 'img/esculturas/fernando-5.webp'),
	 ('2024-11-26', 8, 'img/esculturas/fernando-6.webp'),
	 ('2024-11-26', 8, 'img/esculturas/fernando-7.webp'),
	 ('2024-11-26', 8, 'img/esculturas/fernando-8.webp'),
	 ('2024-11-26', 8, 'img/esculturas/fernando-9.webp'),
	 ('2024-11-26', 9, 'img/esculturas/florentino-1.webp'),
	 ('2024-11-26', 9, 'img/esculturas/florentino-2.webp'),
	 ('2024-11-26', 9, 'img/esculturas/florentino-3.webp'),
	 ('2024-11-26', 9, 'img/esculturas/florentino-4.webp'),
	 ('2024-11-26', 9, 'img/esculturas/florentino-5.webp'),
	 ('2024-11-26', 9, 'img/esculturas/florentino-6.webp'),
	 ('2024-11-26', 9, 'img/esculturas/florentino-7.webp'),
	 ('2024-11-26', 9, 'img/esculturas/florentino-8.webp'),
	 ('2024-11-26', 9, 'img/esculturas/florentino-9.webp'),
	 ('2024-11-26', 10, 'img/esculturas/sarita-1.webp'),
	 ('2024-11-26', 10, 'img/esculturas/sarita-2.webp'),
	 ('2024-11-26', 10, 'img/esculturas/sarita-3.webp'),
	 ('2024-11-26', 10, 'img/esculturas/sarita-4.webp'),
	 ('2024-11-26', 10, 'img/esculturas/sarita-5.webp'),
	 ('2024-11-26', 10, 'img/esculturas/sarita-6.webp'),
	 ('2024-11-26', 10, 'img/esculturas/sarita-7.webp'),
	 ('2024-11-26', 10, 'img/esculturas/sarita-8.webp'),
	 ('2024-11-26', 10, 'img/esculturas/sarita-9.webp'),
	 ('2024-11-26', 11, 'img/esculturas/juanCarlos-1.webp'),
	 ('2024-11-26', 11, 'img/esculturas/juanCarlos-2.webp'),
	 ('2024-11-26', 11, 'img/esculturas/juanCarlos-3.webp'),
	 ('2024-11-26', 11, 'img/esculturas/juanCarlos-4.webp'),
	 ('2024-11-26', 11, 'img/esculturas/juanCarlos-5.webp'),
	 ('2024-11-26', 11, 'img/esculturas/juanCarlos-6.webp'),
	 ('2024-11-26', 11, 'img/esculturas/juanCarlos-7.webp'),
	 ('2024-11-26', 11, 'img/esculturas/juanCarlos-8.webp'),
	 ('2024-11-26', 11, 'img/esculturas/juanCarlos-9.webp'),
	 ('2024-11-26', 12, 'img/esculturas/ramiro-1.webp'),
	 ('2024-11-26', 12, 'img/esculturas/ramiro-2.webp'),
	 ('2024-11-26', 12, 'img/esculturas/ramiro-3.webp'),
	 ('2024-11-26', 12, 'img/esculturas/ramiro-4.webp'),
	 ('2024-11-26', 12, 'img/esculturas/ramiro-5.webp'),
	 ('2024-11-26', 12, 'img/esculturas/ramiro-6.webp'),
	 ('2024-11-26', 12, 'img/esculturas/ramiro-7.webp'),
	 ('2024-11-26', 12, 'img/esculturas/ramiro-8.webp'),
	 ('2024-11-26', 12, 'img/esculturas/ramiro-9.webp'),
	 ('2024-11-26', 13, 'img/esculturas/xavier-1.webp'),
	 ('2024-11-26', 13, 'img/esculturas/xavier-2.webp'),
	 ('2024-11-26', 13, 'img/esculturas/xavier-3.webp'),
	 ('2024-11-26', 13, 'img/esculturas/xavier-4.webp'),
	 ('2024-11-26', 13, 'img/esculturas/xavier-5.webp'),
	 ('2024-11-26', 13, 'img/esculturas/xavier-6.webp'),
	 ('2024-11-26', 13, 'img/esculturas/xavier-7.webp'),
	 ('2024-11-26', 13, 'img/esculturas/xavier-8.webp'),
	 ('2024-11-26', 13, 'img/esculturas/xavier-9.webp'),
	 ('2024-11-26', 14, 'img/esculturas/duilio-1.webp'),
	 ('2024-11-26', 14, 'img/esculturas/duilio-2.webp'),
	 ('2024-11-26', 14, 'img/esculturas/duilio-3.webp'),
	 ('2024-11-26', 14, 'img/esculturas/duilio-4.webp'),
	 ('2024-11-26', 14, 'img/esculturas/duilio-5.webp'),
	 ('2024-11-26', 14, 'img/esculturas/duilio-6.webp'),
	 ('2024-11-26', 14, 'img/esculturas/duilio-7.webp'),
	 ('2024-11-26', 14, 'img/esculturas/duilio-8.webp'),
	 ('2024-11-26', 14, 'img/esculturas/duilio-9.webp'),
	 ('2024-11-26', 15, 'img/esculturas/maricruz-1.webp'),
	 ('2024-11-26', 15, 'img/esculturas/maricruz-2.webp'),
	 ('2024-11-26', 15, 'img/esculturas/maricruz-3.webp'),
	 ('2024-11-26', 15, 'img/esculturas/maricruz-4.webp'),
	 ('2024-11-26', 15, 'img/esculturas/maricruz-5.webp'),
	 ('2024-11-26', 15, 'img/esculturas/maricruz-6.webp'),
	 ('2024-11-26', 15, 'img/esculturas/maricruz-7.webp'),
	 ('2024-11-26', 15, 'img/esculturas/maricruz-8.webp'),
	 ('2024-11-26', 15, 'img/esculturas/maricruz-9.webp'),
	 ('2024-11-26', 16, 'img/esculturas/buenaventura-1.webp'),
	 ('2024-11-26', 16, 'img/esculturas/buenaventura-2.webp'),
	 ('2024-11-26', 16, 'img/esculturas/buenaventura-3.webp'),
	 ('2024-11-26', 16, 'img/esculturas/buenaventura-4.webp'),
	 ('2024-11-26', 16, 'img/esculturas/buenaventura-5.webp'),
	 ('2024-11-26', 16, 'img/esculturas/buenaventura-6.webp'),
	 ('2024-11-26', 16, 'img/esculturas/buenaventura-7.webp'),
	 ('2024-11-26', 16, 'img/esculturas/buenaventura-8.webp'),
	 ('2024-11-26', 16, 'img/esculturas/img/esculturas/buenaventura-9.webp'),
	 ('2024-11-26', 17, 'img/esculturas/fernando-1.webp'),
	 ('2024-11-26', 17, 'img/esculturas/fernando-2.webp'),
	 ('2024-11-26', 17, 'img/esculturas/fernando-3.webp'),
	 ('2024-11-26', 17, 'img/esculturas/fernando-4.webp'),
	 ('2024-11-26', 17, 'img/esculturas/fernando-5.webp'),
	 ('2024-11-26', 17, 'img/esculturas/fernando-6.webp'),
	 ('2024-11-26', 17, 'img/esculturas/fernando-7.webp'),
	 ('2024-11-26', 17, 'img/esculturas/fernando-8.webp'),
	 ('2024-11-26', 17, 'img/esculturas/fernando-9.webp'),
	 ('2024-11-26', 18, 'img/esculturas/florentino-1.webp'),
	 ('2024-11-26', 18, 'img/esculturas/florentino-2.webp'),
	 ('2024-11-26', 18, 'img/esculturas/florentino-3.webp'),
	 ('2024-11-26', 18, 'img/esculturas/florentino-4.webp'),
	 ('2024-11-26', 18, 'img/esculturas/florentino-5.webp'),
	 ('2024-11-26', 18, 'img/esculturas/florentino-6.webp'),
	 ('2024-11-26', 18, 'img/esculturas/florentino-7.webp'),
	 ('2024-11-26', 18, 'img/esculturas/florentino-8.webp'),
	 ('2024-11-26', 18, 'img/esculturas/florentino-9.webp');
INSERT INTO "auth_user" (
    "password",
    "last_login",
    "is_superuser",
    "username",
    "first_name",
    "email",
    "is_staff",
    "is_active",
    "date_joined",
    "last_name"
) VALUES (
    'pbkdf2_sha256$870000$q7jZZSTbg7cV2RdU6ooNko$4k5FrQg30KnKPyG2M2yNC5filhPeaxCOC2ZKri0rZCs=',
    NULL,
    true,
    'admin',
    '',
    'admin@admin.com',
    true,
    true,
    '2024-11-01 22:17:39.218211',
    ''
);